### ISSUE TITLE
Convert libaudit field parsing code to use macros instead of hard-coded error numbers

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-userspace#11]
The audit_rule_interfield_comp_data() and audit_rule_fieldpair_data() option field parsers use over 30 hard-coded numerical error codes to select an error message when errors are detected.  Use meaningfully named macros to make the code easier to understand and verify.

**Comment by rgbriggs** [comment]
Patch posted upstream: https://www.redhat.com/archives/linux-audit/2017-April/msg00004.html

**Comment by stevegrubb** [comment]
applied
