### ISSUE TITLE
RFE: avoid excessive ausearch disk IO when processing a log with a checkpoint

### ISSUE THREAD

**Issue by mvpel** [linux-audit/audit-userspace#112]
The ausearch command, when processing a log file from a checkpoint, opens the audit log and searches from the very beginning of the file, pulling each record and checking the timestamp until it reaches the checkpoint timestamp.

When an audit log gets exceedingly large, this can result in noticeable impact on the IO subsystem, particularly on older machines with slower disks and controllers. On newer systems, it can result in unnecessary SSD wear depending on OS buffer cache patterns.

This issue was noticed when "ausearch" was put into a Splunk pipeline, running a frequent checkpointed ausearch in order to have a near-realtime feed of audit events into the Splunk collector, and was run on a group of diskless nodes NFS-mounting their root and overlay filesystems from a server. A number of systems had accumulated very large audit logs due to an unrelated problem in log rotation, and ausearch had to read an entire 2.5GB audit log each time in order to pull out the ten lines that appeared since the last run a minute prior, crushing the NFS server in the process. (A workaround is in place)

A more efficient implementation of checkpoints is called for, I believe.

I have a couple of approaches in mind as to how to address this issue.

Add the file offset to the checkpoint file, along with the timestamp and the log file's device/inode. Have ausearch use a seek call to jump to that offset in the applicable log and then search for the timestamp from that point, perhaps after moving back a bit in the file in case anything odd happened to the file after the checkpoint was taken. The addition of the offset would need to be handled in such a way as to preserve backwards compatibility with older versions of ausearch reading the checkpoint file.

Do a seek() binary-search for the timestamp, based on the typical audit log record size and the size of the log file itself being over a threshold. Seek to the halfway point of the file and read a timestamp - if it's less than the checkpoint timestamp, seek to 3/4. If you pass the timestamp, seek backwards to 5/8, and so on, in order to get close to the timestamp before beginning to walk through each record looking for it while reading as little of the file as possible to get there

**Comment by mvpel** [comment]
Simply adding a line to the checkpoint file to specify the offset in the log (e.g., offset=<n>) or adding a field to the the output line, will cause previous versions of ausearch to reject it, because [the output line's format is fixed](https://github.com/linux-audit/audit-userspace/blob/master/src/ausearch-checkpt.c#L178) and [unrecognized keys are not allowed](https://github.com/linux-audit/audit-userspace/blob/master/src/ausearch-checkpt.c#L238). And a checkpoint-file format failure results in a [failure of the ausearch command](https://github.com/linux-audit/audit-userspace/blob/master/src/ausearch.c#L113), so adding an offset= line or modifying the output= line poses problems under certain - however unlikely - scenarios.

But since [strtoul() in load_ChkPt()](https://github.com/linux-audit/audit-userspace/blob/master/src/ausearch-checkpt.c#L225) will stop reading the inode= value string at the first non-decimal digit, another value could be added at the end of inode= line (or dev=) which would be ignored by older versions of ausearch, and newer versions would be able to look for the offset after the delimiter within the line, and just keep going if it's reading an older version's checkpoint and doesn't find an offset.

**Comment by burnalting** [comment]
A couple of things:

- The checkpoint file contains details of the last full event processed. As the records (lines) that make up an auditd event in a log file are not always contiguous, simple seeking or binary chops will not work as there may be events whose first lines appear in the log file before the first line of the last full event processed. To improve the read efficiency, I believe some mechanism that maintains (and hence records) the first line offset for the `oldest` non processed event would be required. Perhaps one could store the file offset in the[ _lolnode_ structure](https://github.com/linux-audit/audit-userspace/blob/master/src/ausearch-lol.h#L38) then get this value form the `oldest` _status == L_BUILDING_ member of the list and save that for seeking.

- I don't quite understand the need maintain backwards capability for a _new_ feature in the checkpoint file. Once a new, offset aware, **ausearch** runs and updates the checkpoint file format, I don't believe we need to cater for someone who chooses to back-out **ausearch** to an earlier version and expect any state aware items to also back out. Such requirements are normally met by proper change control processes. Further, I don't believe `overloading` a configuration line item is appropriate (making use of strtoul() features). I believe we should just change the format as required and advise users that the checkpoint state file will not be backwards compatible.

**Comment by stevegrubb** [comment]
I don't see a need to maintain backwards compatibility either. Due to log rotation, I'm not sure what can be done to speed this up.

**Comment by stevegrubb** [comment]
Cleaning up some old issues. It sounds like this ended in an inconclusive state. Is there any reason to keep this issue open?

**Comment by stevegrubb** [comment]
OK, closing it. Thanks for reporting the issue.
