### ISSUE TITLE
Hide specific entries from audit.log

### ISSUE THREAD

**Issue by aurelien-git** [linux-audit/audit-userspace#113]
Hi,
I would like to execute a script that would not be logged by auditd
https://www.thegeekdiary.com/how-to-ignore-disable-specific-auditd-logging-entries/
describe solutions, but I do not find the way to make it works on Debian.
Any idea?

**Comment by stevegrubb** [comment]
This would follow a pattern similar to autrace. (Look at its source code.) 
* You would fork a child process. This would then let you know what pid it will have.
* Then send a rule from the child that is equivalent to
  -a never,exit -F pid=<pid-of-child>
* Then call execve with your target program

For this to work, it must be done as root. Also, I cannot foresee adding a program to the audit package that would allow circumvention of the audit trail.

**Comment by stevegrubb** [comment]
I'm going to close this issue. This is not something that will be added to the audit package. But the recipe is very similar to autrace. The source code for that could be hacked-up to do what's needed.

**Comment by aurelien-git** [comment]
Great thanks I will try it!
