### ISSUE TITLE
Python bindings are broken due to missing stdint.i included

### ISSUE THREAD

**Issue by EccoTheFlintstone** [linux-audit/audit-userspace#120]
I commented on the wrong fix in issue #96 but issue is still closed and I 'm not sure anybody will see the comment as the issue is still closed, so I'm recreating a new issue and adding a copy of my message :

Bug seem to still be present (with latest version 2.8.5 , version 2.8.5-2ubuntu-1 on ubuntu 19.10)
proposed fix by @bigon was
`%include <stdint.i>`

what was commited is
`#include <stdint.i>`

Note the difference between `%include` and `#include` which is a big difference with SWIG
From my tests with :

```
1 - #include <stdint.h>
2 - #include <stdint.i>
3 - %include <stdint.i>

```
wrapper generated by 1 and 2 are the same
wrapper generated by 3 uses a different SWIG function to parse uint32_t and should be ok

quick test to see if it works :

```
import audit
fd = audit.audit_open()
audit.audit_set_enabled(fd, 1)
```

Currently, this is the error we get :

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: in method 'audit_set_enabled', argument 2 of type 'uint32_t'
>>>

```

**Comment by bigon** [comment]
At the time c46c8f2c2ca1806d004f6326bf09244a24a1e981 was comited, it was actually working

I just tested in debian stable/buster and debian unstable. I cannot reproduce that in debian stable, only in unstable, so something has changed (either the python version or swig)

**Comment by EccoTheFlintstone** [comment]
I don't know with which SWIG version the debian/ubuntu packages are compiled, but the tests I performed on my machine were made with swig 3 (3.0.12) on an ubuntu 19.10

**Comment by stevegrubb** [comment]
Strange. I'm not seeing any crash with the reproducer on Fedora 31 (which has swig4). I also don't see anything different changing to %include. So, maybe I'll just change it since it doesn't seem to have any negative effect for me.

**Comment by stevegrubb** [comment]
commit 9b05cec should fix this.

**Comment by bigon** [comment]
@stevegrubb Could you also maybe cherry-pick that to the 2.8 maintenance branch?

(is there a plan to release a 2.8.6 or are you expecting distributions to cherry-pick from that branch?)

**Comment by stevegrubb** [comment]
@bigon I cherry picked the commit. As for a release of 2.8.6...I had been doing some light maintenance with the aim of doing one last update. As its stands right now, I don't have any systems old enough to use in my day to day routine to notice if this combination of patches work right. I also stopped checking picking back in Sept. when the last Fedora distro using 2.8 was near EOL. We might could tag one last version and do a release, but at this point the 3.0 alphas are actually much better than the older 2.8 branch. Even though they say they are alpha's they are in production use on RHEL 8. I'd really recommend moving to it for the next new version of Debian. Things moved around and audisp is gone now, so only new releases should move to it.
