### ISSUE TITLE
Do not build static library for python module

### ISSUE THREAD

**Issue by bigon** [linux-audit/audit-userspace#121]
Hello,

ATM it seems that a static library (`.a` file) is being created when building the auparse python module, this is useless.

Quickly looking, it seems that adding `auparse_la_CFLAGS = -shared` to the binding Makefile prevents the creating of the static library. (the audit module is doing the same already)

I didn't test the resulting module though

**Comment by stevegrubb** [comment]
Fixed by commit a5bcb76. Thanks for reporting this.

**Comment by bigon** [comment]
@stevegrubb are you sure passing `-shared` to `CPPFLAGS` is working? in my tests I used `CFLAGS` like for the other python module (and also `LDFLAGS`)

**Comment by bigon** [comment]
@stevegrubb ping?
