### ISSUE TITLE
auditd start failed in docker

### ISSUE THREAD

**Issue by Mingli-Yu** [linux-audit/audit-userspace#128]
install auditd in a docker container and check the status as below:
 # rpm -q auditd
auditd-2.8.5-r0.0.corei7_64
 # systemctl status auditd
● auditd.service - Security Auditing Service
     Loaded: loaded (/lib/systemd/system/auditd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2020-05-21 07:35:54 UTC; 1s ago
    Process: 306 ExecStart=/sbin/auditd -n (code=exited, status=1/FAILURE)
    Process: 307 ExecStartPost=/sbin/auditctl -R /etc/audit/audit.rules (code=exited, status=1/FAILURE)
   Main PID: 306 (code=exited, status=1/FAILURE)

May 21 07:35:54 fd8b520bfdbe systemd[1]: Started Security Auditing Service.
May 21 07:35:54 fd8b520bfdbe auditd[306]: Started dispatcher: /sbin/audispd pid: 317
May 21 07:35:54 fd8b520bfdbe auditd[306]: Error sending status request (Operation not permitted)
May 21 07:35:54 fd8b520bfdbe auditd[306]: Error sending enable request (Operation not permitted)
May 21 07:35:54 fd8b520bfdbe auditd[306]: Unable to set initial audit startup state to 'enable', exiting
May 21 07:35:54 fd8b520bfdbe audispd[317]: No plugins found, exiting
May 21 07:35:54 fd8b520bfdbe auditd[306]: The audit daemon is exiting.
May 21 07:35:54 fd8b520bfdbe auditd[306]: Error setting audit daemon pid (Operation not permitted)
May 21 07:35:54 fd8b520bfdbe systemd[1]: auditd.service: Main process exited, code=exited, status=1/FAILURE
May 21 07:35:54 fd8b520bfdbe systemd[1]: auditd.service: Failed with result 'exit-code'.

**Comment by rgbriggs** [comment]
On 2020-05-21 01:00, Mingli-Yu wrote:
> ● auditd.service - Security Auditing Service
> May 21 07:35:54 fd8b520bfdbe auditd[306]: Error sending status request (Operation not permitted)
> May 21 07:35:54 fd8b520bfdbe auditd[306]: Error sending enable request (Operation not permitted)
> May 21 07:35:54 fd8b520bfdbe auditd[306]: Error setting audit daemon pid (Operation not permitted)

There is not enough information given to be certain, but it is likely
that this is being run in a user or PID namespace which is not currently
supported.  There is also a chance CAP_AUDIT_CONTROL is not given.
Please see: https://bugzilla.redhat.com/show_bug.cgi?id=1397236

**Comment by Mingli-Yu** [comment]
Per https://www.redhat.com/archives/linux-audit/2018-July/msg00078.html, seems the container support doesn't work.

**Comment by stevegrubb** [comment]
Running inside a container is not supported. At most you can set local_events = no and aggregate logs in a container. But not for the local system.
