### ISSUE TITLE
Unreachable call to auparse_feed_age_events in example code

### ISSUE THREAD

**Issue by MatthijsBrink** [linux-audit/audit-userspace#137]
`
if (retval == 0 && auparse_feed_has_data(au))
	auparse_feed_age_events(au);` 
The above is an always false condition which means `auparse_feed_age_events(au)` is never called. This is due to the condition in the do while loop: `do ... while (retval == -1 && ...)` 

https://github.com/linux-audit/audit-userspace/blob/35fe03e660e7f49861d1d17c80fe6409eea4e26a/contrib/plugin/audisp-example.c#L114

**Comment by stevegrubb** [comment]
Thanks for reporting this. Should be fixed by commit fbec491.
