### ISSUE TITLE
RFE: Add filter for path to ignore filesystem types

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-userspace#15]
Tracefs or debugfs were causing hundreds to thousands of PATH records to
be associated with the init_module and finit_module SYSCALL records on a                                                                                   few modules when the following rule was in place for startup:
        -a always,exit -F arch=x86_64 -S init_module -F key=mod-load
 
Add the new "path" filter list anchored in __audit_inode_child() to
filter out PATH records from uninteresting filesystem types, "fstype",
keying on their kernel hexadecimal 4-octet magic identifier.

An example rule would look like:
        -a never,path -F fstype=0x74726163 -F key=ignore_tracefs
        -a never,path -F fstype=0x64626720 -F key=ignore_debugfs

See: https://github.com/linux-audit/audit-kernel/issues/8
Test case: https://github.com/linux-audit/audit-testsuite/issues/42

**Comment by rgbriggs** [comment]
Kernel patch posted upstream:
https://www.redhat.com/archives/linux-audit/2017-April/msg00011.html
https://www.redhat.com/archives/linux-audit/2017-April/msg00012.html

Userspace patch posted upstream:
https://www.redhat.com/archives/linux-audit/2017-April/msg00009.html

**Comment by rgbriggs** [comment]
Userspace patch v2 posted upstream:
https://www.redhat.com/archives/linux-audit/2017-June/msg00065.html
Change AUDIT_FILTER_PATH to AUDIT_FILTER_FS and change filter list name "path" to "filesystem".

For consistency the kernel AUDIT_FILTER_PATH macro  will need to be changed too in the patches for https://github.com/linux-audit/audit-kernel/issues/8

**Comment by rgbriggs** [comment]
Userspace patch v3 posted upstream:
https://www.redhat.com/archives/linux-audit/2017-June/msg00071.html
Update feature bitmap macro to reflect the filter name change.
https://www.redhat.com/archives/linux-audit/2017-June/msg00072.html

**Comment by stevegrubb** [comment]
applied.
