### ISSUE TITLE
Multiple definition of free_config and clear_config when static building

### ISSUE THREAD

**Issue by hube12** [linux-audit/audit-userspace#152]
Hello,
There is still currently some build errors when building the static library, it also worth noting that since #147 the current bug in 3.0 was fixed thus the only way to build a static lib is to either apply that patch or build the current branch.

```sh
/usr/bin/ld:  /audit-userspace/linux-audit-audit-userspace-0771ea4/auparse/auditd-config.c:82: multiple definition of `clear_config'; 
auditd-auditd-config.o:/audit-userspace/linux-audit-audit-userspace-0771ea4/src/auditd-config.c:312: first defined here

/usr/bin/ld: /audit-userspace/linux-audit-audit-userspace-0771ea4/auparse/auditd-config.c:361: multiple definition of `free_config'; 
auditd-auditd-config.o:/audit-userspace/linux-audit-audit-userspace-0771ea4/src/auditd-config.c:1986: first defined here
```

**Comment by stevegrubb** [comment]
I renamed a couple auparse functions and checked them in. Hopefully, this fixes the issue.

**Comment by hube12** [comment]
Hi, thanks for your work I opened #153 with the rest of the changes, have a wonderful day.

**Comment by stevegrubb** [comment]
Hmm. The pull request is quite a bit more than I thought it would be. Thanks. There are a couple that I might want to rename. I might download the patch, doctor it up and apply manually. If I do that right, it should still link back to you. That has been my only hesitation in accepting the patch.

**Comment by hube12** [comment]
Hi, I totally get it, I am happy either way, I don't see that as a big changes, more a fix to allow a edge case (static compilation), thanks for taking that into account !

**Comment by stevegrubb** [comment]
The patch has been applied with modifications. Thanks for sending it. If you notice any problems that it should have covered, please feel free to re-open this issue.
