### ISSUE TITLE
Porting to Android

### ISSUE THREAD

**Issue by wushifu32** [linux-audit/audit-userspace#158]
How to run it in Android platform? Is there a plan porting it to Android platform?

**Comment by stevegrubb** [comment]
I personally have no plans for porting this to Android. I also had no plans to port it to other Linux distributions. But someone else using those distributions saw value in it being there and took it upon themselves to port and become the maintainer on that distribution. That is how it spreads to other platforms. If you would like to port it, I'm fine with that.

**Comment by stevegrubb** [comment]
Going to close this out. Anyone that wants to can push this to Android. There's nothing identified as needing to be done by this project.
