### ISSUE TITLE
Proposed worked example for auditd(8) documentation

### ISSUE THREAD

**Issue by ringerc** [linux-audit/audit-userspace#162]
It'd be great to see an example in `auditd(8), `ausearch(8)` and/or `aureport(8)` docs that shows a few fully worked examples, taking account of common configuration like the default `never,task` rule that will otherwise confuse new users.

I had no idea `auditd` was so amazing because the docs just didn't give me any clue how powerful it is, or make it easy to get started trying it out. I got stuck for some time with it seeming to just "not work" because of the `never,task` rule, too.

## Proposed full example

Generate a summary of all syscalls made by a process.

```
# Enable auditing on new processes if it's disabled - see "DISABLED BY DEFAULT" in "auditd(8)"
auditctl -d never,task
# Match all system calls for the target process. Note that this will not audit syscalls in child processes of the audited process.
auditctl -A always,exit -S all -F exe=/bin/ls -k audit_ls
# Run the program to generate an audit trail
ls
# view individual audit records for the rule, showing names of syscalls, users, etc instead of numbers
ausearch -i -k audit_ls
# summarise the syscalls made by the audited process
ausearch --format raw -k audit_ls | aureport -s -i --summary
# Remove the audit rules if desired
auditctl -d -k audit_ls
```

Note that I would prefer this worked example to instead start with something like:

```
# Enable auditing for new instances of the target executable. See "DISABLED BY DEFAULT" in "auditd(8)"
auditctl -A always,task -F exe=/bin/ls -k audit_ls
```

but couldn't get a per-task exception to work, so I've left it as above.

----

## Warn users about the `never,task` rule

I also propose a `DISABLED BY DEFAULT` section in `auditd(8)`, reading something like this

> DISABLED BY DEFAULT
>
> On many systems `auditd` is configured to install an `-a never,task` rule by default.
>
> This rule sets a flag on every new process that skips all audit rule processing for that process, so the small performance overhead imposed by syscall auditing is completely eliminated. If you want to use auditd, you will need to remove this rule with `auditctl -d never,task` or insert more specific rules for targeted processes above it, e.g. `auditctl -A always,task -x /executable/to/audit`.
>
> If you have defined audit rules that are not matching when they should, check `auditctl -l` to make sure there is no `never,task` rule there.
>
> Note that any processes that were started with a `never,task` rule will be ignored for auditing purposes even 

It should have a clear x-ref to it in `ausearch(8)` and `auditctl(8)` that is easily found with keywords like "empty" or "match" or "nothing" in the NOTES section, pointing users to why their rules may not be matching anything or their searches are failing to find any hits for rules they defined. Something like:

This should also be x-ref'd from `PERFORMANCE TIPS` in `auditctl(8)`.

## A few more examples

I also suggest the existing `auditctl(8)` example

> To see all syscalls made by a specific program:
>
> `auditctl -a always,exit -S all -F pid=1005`

become

> To see all syscalls made by a specific program:
>
> `# by pid:`
> `auditctl -a always,exit -S all -F pid=1005`
> `# by executable name`
> `auditctl -a always,exit -S all -F comm=ls`
> `# by executable path`
> `auditctl -a always,exit -S all -F exe=/bin/ls`

as they're particularly obvious things people will want to do.

**Comment by stevegrubb** [comment]
I added some more text to the auditctl man page. Does the new text cover everything?

**Comment by stevegrubb** [comment]
Closing this. Improved documentation is in the 3.0.3 release. If you have more suggestions, please open a new request. Thanks!
