### ISSUE TITLE
ausearch(8) should "See also aureport(8)"

### ISSUE THREAD

**Issue by ringerc** [linux-audit/audit-userspace#163]
I was on the verge of writing my own summary tool when I noticed that there's an `aureport` tool to supplement the output from `ausearch` .

I realise that it's indirectly referenced by `auditd(8)`, but it'd be nice to have a direct xref between closely related tools like this, especially since their names don't start with `audit`

**Comment by stevegrubb** [comment]
Besides ausearch, there are 4 different utilities that do something different with the logs. Not sure where we draw the line cross referencing things. :-)  The ausearch man page was updated.
