### ISSUE TITLE
Incorrect/missing data in audit PATH records

### ISSUE THREAD

**Issue by shailcompsit** [linux-audit/audit-userspace#168]
Environment: 
```
[root@myvm ~]# auditctl -v
auditctl version 2.8.1

[root@myvm ~]# cat /etc/oracle-release
Oracle Linux Server release 7.5
```
Operation:
```
[root@myvm malicious]# auditctl -l
-w /root/shailcompsit -p wa -k rule1_root_shailcompsit

[root@myvm malicious]# pwd
/root/shailcompsit/malicious

[root@myvm malicious]# cp 123_abc.txt 124_abc.txt
```
Audit Records:
```
type=SYSCALL msg=audit(1618445541.631:468228): arch=c000003e syscall=2 success=yes exit=4 a0=7ffe8be377f0 a1=c1 a2=1c9 a3=7ffe8be36560 items=3 ppid=8009 pid=7396 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 ses=6687 tty=pts2 comm="cp" exe="/usr/bin/cp" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key="rule1_root_shailcompsit"
type=CWD msg=audit(1618445541.631:468228):  cwd="/root/shailcompsit/malicious"
type=PATH msg=audit(1618445541.631:468228): item=0 name="124_abc.txt" inode=36028359 dev=fc:01 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:object_r:admin_home_t:s0
type=PATH msg=audit(1618445541.631:468228): item=1 name=(null) inode=36028359 dev=fc:01 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:object_r:admin_home_t:s0
type=PATH msg=audit(1618445541.631:468228): item=2 name=(null) inode=36047150 dev=fc:01 mode=0100711 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:object_r:admin_home_t:s0
type=EOE msg=audit(1618445541.631:468228):
```

I see few issues with the audit records here,

1. nametype or objtype missing for PATH records. 
2. General observation is first PATH record (item=0) is directory, but here name field has filename "124_abc.txt" and mode=040755 is directory. Also, the inode value "36028359"  belongs to directory "/root/shailcompsit/malicious/".

**Comment by rgbriggs** [comment]
On 2021-04-15 01:09, Shailesh Kapse wrote:
> auditctl version 2.8.1
> Oracle Linux Server release 7.5
> 1. nametype or objtype missing for PATH records. 
> 2. General observation is first PATH record (item=0) is directory, but here name field has filename "124_abc.txt" and mode=040755 is directory. Also, the inode value "36028359"  belongs to directory "/root/shailcompsit/malicious/". 

1. This appears to be a kernel issue so should have been filed against https://github.com/linux-audit/audit-kernel
2. This appears to be a very old kernel where nametype/objtype weren't implemented yet.
3. There have been a number of other fixes to this area of code since then.
Please contact your vendor for a more up to date kernel, or roll your own from a recent upstream.

**Comment by pcmoore** [comment]
Nothing much to add beyond what @rgbriggs already said.  Since this is both primarily a kernel issue and the affected kernel is an old distro kernel, likely with a variety of backports, there is not much we can do here - I'm going to close the upstream issue.
