### ISSUE TITLE
 alarm(5) in shutdown_events() can ensure thar the auditd can exit?

### ISSUE THREAD

**Issue by e06620227** [linux-audit/audit-userspace#204]
The following is the relevant code snippet before the end of main。we can see auditd process set an alarm clock before auditd main() return。after setting the alarm，if main() takes more than  5 seconds to end，the thread_killer will be call fisrt，and then call the clean_exit() (atexit(clean_exit) in main()), When the audit event load is heavy, there is no signal to wake up audit_set_pid()
https://github.com/linux-audit/audit-userspace/issues/203

//the last lines of main
	ev_signal_stop(loop, &sigchld_watcher);

	close_down(); // set alarm(5)
	free_config(&config);
	ev_default_destroy();

	return 0;
}

static void close_down(void)
{
	struct sigaction sa;

	/* We are going down. Give the event thread a chance to shutdown.
	   Just in case it hangs, set a timer to get us out of trouble. */
	sa.sa_flags = 0 ;
	sigemptyset( &sa.sa_mask ) ;
	sa.sa_handler = thread_killer;
	sigaction( SIGALRM, &sa, NULL );
	shutdown_events();
}

void shutdown_events(void)
{
	/* Give it 5 seconds to clear the queue */
	alarm(5);

	// Nudge the flush thread
	pthread_cond_signal(&do_flush);
	pthread_join(flush_thread, NULL);

	free((void *)format_buf);
	if (log_file)
		fclose(log_file);
	auparse_destroy_ext(NULL, AUPARSE_DESTROY_ALL);
}

**Comment by stevegrubb** [comment]
Why do we have 2 issues open for the same problem?  I found a couple signals that were not masked for the flush_thread - which have nothing to do with the alarm signal. What do you have for flush setting in auditd.conf? My guess is that it's busy flushing. But when I add a sleep(60) right after the alarm, it exits exactly in 5 seconds. So, the signal isn't masked.

**Comment by e06620227** [comment]
> Why do we have 2 issues open for the same problem? I found a couple signals that were not masked for the flush_thread - which have nothing to do with the alarm signal. What do you have for flush setting in auditd.conf? My guess is that it's busy flushing. But when I add a sleep(60) right after the alarm, it exits exactly in 5 seconds. So, the signal isn't masked.
@stevegrubb 

You are right. The signal is not masked.  But when I continuously trigger a large number of audit events in system，then add a sleep(10) after the alarm, it can't exit，

Jun  8 18:28:17 localhost auditd[826144]: Audit daemon rotating log files
Jun  8 18:28:22 localhost auditd[826144]: Audit daemon rotating log files
Jun  8 18:28:27 localhost auditd[826144]: Audit daemon rotating log files
Jun  8 18:28:32 localhost auditd[826144]: Audit daemon rotating log files
Jun  8 18:28:37 localhost auditd[826144]: Audit daemon rotating log files
Jun  8 18:28:43 localhost auditd[826144]: Audit daemon rotating log files
Jun  8 18:28:48 localhost auditd[826144]: Audit daemon rotating log files
Jun  8 18:28:53 localhost auditd[826144]: Audit daemon rotating log files
Jun  8 18:28:58 localhost auditd[826144]: Audit daemon rotating log files
Jun  8 18:29:03 localhost auditd[826144]: Audit daemon rotating log files
Jun  8 18:29:06 localhost auditd[826144]: ========== test: main() sleep 10s before returning =============
Jun  8 18:29:06 localhost [/bin/bash]: [service auditd stop] return code=[0], execute success by [root(uid=0)] from [pts/2 (9.5.21.209)]
Jun  8 18:29:11 localhost auditd[826144]: =========== test: enter thread_killer(): sendto timeout, sig=[14] =============
Jun  8 18:29:11 localhost auditd[826144]: The audit daemon is exiting.
Jun  8 18:30:00 localhost systemd[1]: Starting system activity accounting tool...
Jun  8 18:30:00 localhost systemd[1]: sysstat-collect.service: Succeeded.
Jun  8 18:30:00 localhost systemd[1]: Started system activity accounting tool.
Jun  8 18:30:08 localhost kernel: [379139.038327] audit: audit_backlog=65 > audit_backlog_limit=64
Jun  8 18:30:08 localhost kernel: [379139.038331] audit: audit_lost=1 audit_rate_limit=0 audit_backlog_limit=64
Jun  8 18:30:08 localhost kernel: [379139.038334] audit: backlog limit exceeded
Jun  8 18:30:08 localhost kernel: [379139.038360] audit: audit_backlog=65 > audit_backlog_limit=64
Jun  8 18:30:08 localhost kernel: [379139.038363] audit: audit_lost=2 audit_rate_limit=0 audit_backlog_limit=64
Jun  8 18:30:08 localhost kernel: [379139.038365] audit: backlog limit exceeded
Jun  8 18:30:08 localhost kernel: [379139.038393] audit: audit_backlog=65 > audit_backlog_limit=64
Jun  8 18:30:08 localhost kernel: [379139.038396] audit: audit_lost=3 audit_rate_limit=0 audit_backlog_limit=64
Jun  8 18:30:08 localhost kernel: [379139.038397] audit: backlog limit exceeded
Jun  8 18:30:08 localhost kernel: [379139.038402] audit: audit_backlog=65 > audit_backlog_limit=64
Jun  8 18:31:10 localhost kernel: [379200.478344] audit_log_start: 602 callbacks suppressed
Jun  8 18:31:10 localhost kernel: [379200.478348] audit: audit_backlog=65 > audit_backlog_limit=64
Jun  8 18:31:10 localhost kernel: [379200.478351] audit: audit_lost=206 audit_rate_limit=0 audit_backlog_limit=64
Jun  8 18:31:10 localhost kernel: [379200.478353] audit: backlog limit exceeded
Jun  8 18:31:10 localhost kernel: [379200.478376] audit: audit_backlog=65 > audit_backlog_limit=64
Jun  8 18:31:10 localhost kernel: [379200.478379] audit: audit_lost=207 audit_rate_limit=0 audit_backlog_limit=64
Jun  8 18:31:10 localhost kernel: [379200.478381] audit: backlog limit exceeded
Jun  8 18:31:10 localhost kernel: [379200.478771] audit: audit_backlog=65 > audit_backlog_limit=64
Jun  8 18:31:10 localhost kernel: [379200.478775] audit: audit_backlog=65 > audit_backlog_limit=64
Jun  8 18:31:10 localhost kernel: [379200.478778] audit: audit_lost=208 audit_rate_limit=0 audit_backlog_limit=64
Jun  8 18:31:10 localhost kernel: [379200.478779] audit: backlog limit exceeded
Jun  8 18:31:22 localhost kernel: [379212.766183] audit_log_start: 599 callbacks suppressed
Jun  8 18:31:22 localhost kernel: [379212.766187] audit: audit_backlog=65 > audit_backlog_limit=64
Jun  8 18:31:22 localhost kernel: [379212.766191] audit: audit_lost=409 audit_rate_limit=0 audit_backlog_limit=64
Jun  8 18:31:22 localhost kernel: [379212.766193] audit: backlog limit exceeded


auditd.conf

#
# This file controls the configuration of the audit daemon
#

local_events = yes
write_logs = yes
log_file = /var/log/audit/audit.log
log_group = root
log_format = ENRICHED
flush = INCREMENTAL_ASYNC
freq = 50
max_log_file = 8
num_logs = 5
priority_boost = 4
disp_qos = lossy
dispatcher = /sbin/audispd
name_format = NONE
##name = mydomain
max_log_file_action = ROTATE
space_left = 75
space_left_action = SYSLOG
verify_email = yes
action_mail_acct = root
admin_space_left = 50
admin_space_left_action = SUSPEND
disk_full_action = SUSPEND
disk_error_action = SUSPEND
use_libwrap = yes
##tcp_listen_port = 60
tcp_listen_queue = 5
tcp_max_per_addr = 1
##tcp_client_ports = 1024-65535
tcp_client_max_idle = 0
enable_krb5 = no
krb5_principal = auditd
##krb5_key_file = /etc/audit/audit.key
distribute_network = no

**Comment by stevegrubb** [comment]
OK, thanks for the info. There are 2 threads: the main thread and a flush thread. The current design is to do an orderly shutdown by asking the flush thread to exit and waiting for it. I suppose we could proceed with termination by not doing a join and simply doing a fsync() in the main thread on the way out.

**Comment by e06620227** [comment]
> Commit [17329aa](https://github.com/linux-audit/audit-userspace/commit/17329aadedcb8b9b1eb877f5a1f50b461746bb88) should address this issue.

@stevegrubb 

Patched  it  then I continuously trigger a large number of audit events in system，auditd can't exit，it's suspended to  audit_set_pid(fd, 0, WAIT_NO) in clean_exit.  it's call stack is in issues https://github.com/linux-audit/audit-userspace/issues/203

exit logs below：

Jun 10 10:22:15 localhost auditd[2464609]: Audit daemon rotating log files
Jun 10 10:22:18 localhost auditd[2464609]: The audit daemon is exiting.
Jun 10 10:22:18 localhost [/bin/bash]: [service auditd stop] return code=[0], execute success by [root(uid=0)] from [pts/1 (9.5.21.209)]
Jun 10 10:23:20 localhost kernel: [522730.462197] audit_log_start: 19770 callbacks suppressed
Jun 10 10:23:20 localhost kernel: [522730.462201] audit: audit_backlog=65 > audit_backlog_limit=64
Jun 10 10:23:20 localhost kernel: [522730.462205] audit: audit_lost=4898 audit_rate_limit=0 audit_backlog_limit=64
Jun 10 10:23:20 localhost kernel: [522730.462207] audit: backlog limit exceeded
Jun 10 10:23:20 localhost kernel: [522730.462318] audit: audit_backlog=65 > audit_backlog_limit=64
Jun 10 10:23:20 localhost kernel: [522730.462322] audit: audit_lost=4899 audit_rate_limit=0 audit_backlog_limit=64
Jun 10 10:23:20 localhost kernel: [522730.462324] audit: backlog limit exceeded
Jun 10 10:23:20 localhost kernel: [522730.462335] audit: audit_backlog=65 > audit_backlog_limit=64
Jun 10 10:23:20 localhost kernel: [522730.462338] audit: audit_lost=4900 audit_rate_limit=0 audit_backlog_limit=64
Jun 10 10:23:20 localhost kernel: [522730.462340] audit: backlog limit exceeded

**Comment by stevegrubb** [comment]
I looked at the code for audit_set_pid(), there is nothing there that should make it hang. At that point it's deregistering itself with a no wait syscall. It should send it and return. If it's hanging in the kernel, there's not much I can do. There are no syscalls other than a sendto.
