### ISSUE TITLE
Auditd parent process will double free the config if child fails

### ISSUE THREAD

**Issue by yixiangzhike** [linux-audit/audit-userspace#207]
In the commit [43cda5a07bc944362299e7f9ee12abf5b6235159](https://github.com/linux-audit/audit-userspace/commit/43cda5a07bc944362299e7f9ee12abf5b6235159), add "free_config(&config);" for parent in the become_daemon() function, but if child fails, parent aborted(core dumped) because it will double free the config.

**Comment by stevegrubb** [comment]
OK, I moved the free_config under the success path in commit d89e564. The only way the child fails is not being able to open /dev/null, dup the descriptor to it, or fails chdir to /. None of these should happen in practice since it starts early in the boot and has all capabilities.

**Comment by stevegrubb** [comment]
Closing this issue. Thanks for the report.
