### ISSUE TITLE
Memory leak in audisp-plugin

### ISSUE THREAD

**Issue by shashankakula18** [linux-audit/audit-userspace#208]
Hi 
I have an issue regarding Audisp-Plugin which is leaking memory since migration to py3 from py2. I also observed that Auparse module's behavior is different in py3 and py2, I don't know if this is the actual reason for leak. There is no leak in py2 so I believe there can be a fix possible with py3

Can you please help me to get this fixed?

**Comment by stevegrubb** [comment]
I presume this is for 2.3.2. If so, this is way out of support. If this can be reproduced on the current 3.0.3 release, then I can look into it. If the current release does not leak, then take a look at the history of commits for the python bindings. Raise the leak with your linux distro.

**Comment by stevegrubb** [comment]
Closing out this issue. If there is a leak in recent code, please re-open this issue.
