### ISSUE TITLE
The audit can not record correct user name in audit.log

### ISSUE THREAD

**Issue by yizhao1** [linux-audit/audit-userspace#209]
I found this issue both on Fedora 33 (kernel 5.13.8-100.fc33.x86_64, audit 3.0.3) and Yocto (kernel 5.10.53, audit 3.0.4)

In short, if we add a user and delete it immediately, and then add a new user with a different username but the same uid, the audit will record the old username in audit.log instead of the new username. 

Here are the detail steps to reproduce:

# Clean all audit rules:

[test@localhost ~]$ sudo auditctl -D
No rules
[test@localhost ~]$ sudo auditctl -l
No rules

# Add a user named olduser, then delete it.

[test@localhost ~]$ sudo useradd olduser
[test@localhost ~]$ cat /etc/passwd |grep olduser
olduser:x:1002:1002::/home/olduser:/bin/bash
[test@localhost ~]$ 
[test@localhost ~]$ sudo userdel olduser
[test@localhost ~]$ 

# Add a user named newuser
# Make sure its uid is same with olduser.

[test@localhost ~]$ sudo useradd newuser
[test@localhost ~]$ cat /etc/passwd |grep newuser
newuser:x:1002:1002::/home/newuser:/bin/bash
[test@localhost ~]$ 
[test@localhost ~]$ sudo passwd newuser

# Add an audit rule to watch file /home/newuser/1
[test@localhost ~]$ sudo auditctl -w /home/newuser/1 -k HOME
[test@localhost ~]$ sudo auditctl -l
-w /home/newuser/1 -p rwxa -k HOME
[test@localhost ~]$ 

# Login with newuser and ls/cat file /home/newuser/1
[test@localhost ~]$ su - newuser
Password: 
[newuser@localhost ~]$ ls
[newuser@localhost ~]$ pwd
/home/newuser
[newuser@localhost ~]$ echo "something written by newuser" >> 1
[newuser@localhost ~]$ ls -lt 1
-rw-r--r--. 1 newuser newuser 29 Aug 10 16:45 1
[newuser@localhost ~]$ cat 1
something written by newuser
[newuser@localhost ~]$ 

# Check the audit.log
# The UID/EUID/FSUID is olduser, it should be newuser. The GID/EGID/SGID is newuser, this is correct.

type=SYSCALL msg=audit(1628585120.537:446): arch=c000003e syscall=191 success=no exit=-61 a0=7ffcb4c8be42 a1=56536a193b48 a2=0 a3=0 items=1 ppid=2259 pid=2302 auid=1000 uid=1002 gid=1002 euid=1002 suid=1002 fsuid=1002 egid=1002 sgid=1002 fsgid=1002 tty=pts1 ses=2 comm="ls" exe="/usr/bin/ls" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key="HOME"^]ARCH=x86_64 SYSCALL=getxattr AUID="test" UID="olduser" GID="newuser" EUID="olduser" SUID="olduser" FSUID="olduser" EGID="newuser" SGID="newuser" FSGID="newuser"
type=CWD msg=audit(1628585120.537:446): cwd="/home/newuser"
type=PATH msg=audit(1628585120.537:446): item=0 name="1" inode=1046537 dev=fd:02 mode=0100644 ouid=1002 ogid=1002 rdev=00:00 obj=unconfined_u:object_r:user_home_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0^]OUID="olduser" OGID="newuser"
type=PROCTITLE msg=audit(1628585120.537:446): proctitle=6C73002D2D636F6C6F723D6175746F002D6C740031
type=SYSCALL msg=audit(1628585122.325:447): arch=c000003e syscall=257 success=yes exit=3 a0=ffffff9c a1=7ffef55cee40 a2=0 a3=0 items=1 ppid=2259 pid=2303 auid=1000 uid=1002 gid=1002 euid=1002 suid=1002 fsuid=1002 egid=1002 sgid=1002 fsgid=1002 tty=pts1 ses=2 comm="cat" exe="/usr/bin/cat" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key="HOME"^]ARCH=x86_64 SYSCALL=openat AUID="test" UID="olduser" GID="newuser" EUID="olduser" SUID="olduser" FSUID="olduser" EGID="newuser" SGID="newuser" FSGID="newuser"
type=CWD msg=audit(1628585122.325:447): cwd="/home/newuser"

**Comment by stevegrubb** [comment]
Thanks for reporting this problem. Commit 8662f61 should solve this problem.

**Comment by yizhao1** [comment]
> Thanks for reporting this problem. Commit [8662f61](https://github.com/linux-audit/audit-userspace/commit/8662f61108f8b9365f96ef49ca8ca331a7880f24) should solve this problem.

Thanks for the quick response. This patch works for me.
