### ISSUE TITLE
Automatically restart the auditd service when the service is terminated unexpectedly.

### ISSUE THREAD

**Issue by StevenYGui** [linux-audit/audit-userspace#211]
Is it possible to add a line "Restart=on-failure" in file "init.d/auditd.service", then let systemd to automatically restart the auditd service when the service is terminated unexpectedly?
Auditd is an important service in linux, so it is better if it keeping actively.

**Comment by stevegrubb** [comment]
The main reason that is not done is because auditd halts when it finds a problem in its config file. It it were automatically restarted, that would be unhelpful. I'm also not sure of the interaction between systemd and the service command. If you kill auditd with the service stop command and systemd restarts it...that also is not helpful.

**Comment by StevenYGui** [comment]
yes, it can not restart auditd if stopped by service command, but it is useful for "killing -9", maybe can avoid misoperations or simple attacks.

**Comment by travier** [comment]
As per [systemd.service (Restart=)](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=):

```
When the death of the process is a result of systemd operation (e.g. service stop or restart), the service will not be restarted.
```

And also [systemd.service (RestartPreventExitStatus=)](https://www.freedesktop.org/software/systemd/man/systemd.service.html#RestartPreventExitStatus=):

```
Takes a list of exit status definitions that, when returned by the main service process, will prevent automatic service restarts, regardless of the restart setting configured with Restart=. 
```

We could have:

```
[Service]
Restart=on-failure
RestartPreventExitStatus=<wrong config exit code here>
```

**Comment by travier** [comment]
From https://github.com/linux-audit/audit-userspace/blob/master/src/auditd.c#L714, it's `6`. Making a PR.
