### ISSUE TITLE
auditd fails to start if name_format=NUMERIC + host not found in DNS

### ISSUE THREAD

**Issue by cyb3rz3us** [linux-audit/audit-userspace#212]
**Preface**

I understand that what I discuss below may not truly be an issue (and therefore possibly not a defect) but after lots of digging, I still haven't found anything about this specific scenario so I thought this would be a good place to ask.

**General**

- **OS:** CentOS
- **auditd ver:** 2.8.5

**Issue**

Discovered that if I set `name_format=NUMERIC` in `/etc/audit/auditd.conf`, the **auditd** service fails to start if the server's hostname is unresolvable via DNS.  In addition, the following error is seen via `journalctl -xe`:

`auditd[13885]: Cannot resolve hostname ******* (Name or service not known)`

I also discovered that the missing host must be added to the DNS server as it appears **auditd** does not check the local `/etc/hosts` file so I am wondering if **auditd** just doesn't utilize NSS.

**Questions**

* Does **auditd** utilize NSS?
* Is **auditd** failing to start in these conditions expected behavior?
* Can **auditd** be configured to still use `name_format=NUMERIC` and start normally despite not being able to resolve the host in question?

Thanks in advance...

**Comment by stevegrubb** [comment]
auditd uses getaddrinfo to resolve the address for validation. The man page says: In order to use this option, you might want to test that 'hostname -i'  or  'domainname -i'  returns  a numeric address.

**Comment by cyb3rz3us** [comment]
Thanks @stevegrubb - I clearly made an error here which was I thought that `nslookup` utilized NSS which I have just learned it does not.  I should have used ping (or any tool that uses NSS) during my troubleshooting.

Apologies for any waste of time - but I did learn so in the end, it was beneficial...Thank you again...
