### ISSUE TITLE
BUG: README refers to a "README-install" file which does not exist

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-userspace#213]
The main README file directs users to the README-install file for instructions on building the audit-userspace tools; unfortunately that file does not exist:
```
% git show-ref HEAD
cfdb47144c5a11ee561d32155a5ef8832fbd0cf9 refs/remotes/github/HEAD
% grep "README" README
See the README-install File.
% find . -name "README*"
./src/libev/README
./rules/README-rules
./audisp/plugins/ids/README.md
./README
```

**Comment by pcmoore** [comment]
It would appear that information is in the INSTALL.tmp file for some odd reason ... ?
* https://github.com/linux-audit/audit-userspace/blob/master/INSTALL.tmp

**Comment by stevegrubb** [comment]
Commit f47c7fe should fix this. TBH, the whole README page needs a do-over.
