### ISSUE TITLE
fix macro definition check

### ISSUE THREAD

**Issue by vigneshoff** [linux-audit/audit-userspace#218]
Hi,

I think still some of the if macro checks need to be fixed.

Faced build issues with the HAVE_DECL_AUDIT_FEATURE_VERSION macro when building linux version below 3.13, as the audit feature mainlined from 3.13
https://github.com/torvalds/linux/commit/3eaded86ac3e7f00fb3eeb8162d89e9a34e42fb0

libaudit.c: In function 'audit_set_feature':
libaudit.c:564:24: error: storage size of 'f' isn't known
  struct audit_features f;
                        ^
libaudit.c:567:11: warning: implicit declaration of function 'AUDIT_FEATURE_TO_MASK' [-Wimplicit-function-declaration]
  f.mask = AUDIT_FEATURE_TO_MASK(feature);
           ^
libaudit.c: In function 'audit_request_features':
libaudit.c:588:24: error: storage size of 'f' isn't known
  struct audit_features f;
                        ^
libaudit.c: In function 'audit_set_loginuid_immutable':
libaudit.c:606:31: error: 'AUDIT_FEATURE_LOGINUID_IMMUTABLE' undeclared (first use in this function)
  return audit_set_feature(fd, AUDIT_FEATURE_LOGINUID_IMMUTABLE, 1, 1);
                               ^
libaudit.c:606:31: note: each undeclared identifier is reported only once for each function it appears in
Makefile:864: recipe for target 'libaudit.lo' failed
make[5]: *** [libaudit.lo] Error 1
make[5]: *** Waiting for unfinished jobs....

netlink.c: In function 'adjust_reply':
netlink.c:151:5: error: 'struct audit_reply' has no member named 'features'
  rep->features = NULL;
     ^
netlink.c:177:7: error: 'struct audit_reply' has no member named 'features'
    rep->features =  NLMSG_DATA(rep->nlh);
       ^
Makefile:864: recipe for target 'netlink.lo' failed

Attaching patch for the review.

Thanks
Vignesh

```
From 79bf733b9fce0513c9242da7438cd20929ac285e Mon Sep 17 00:00:00 2001
From: Vignesh R <vignesh.r@timesys.com>
Date: Thu, 30 Sep 2021 17:56:31 +0530
Subject: [PATCH] fix if definition check

---
 lib/libaudit.c         | 6 +++---
 lib/netlink.c          | 4 ++--
 src/auditctl-listing.c | 2 +-
 src/auditctl.c         | 4 ++--
 4 files changed, 8 insertions(+), 8 deletions(-)

diff --git a/lib/libaudit.c b/lib/libaudit.c
index 0d54de9..bf3c22b 100644
--- a/lib/libaudit.c
+++ b/lib/libaudit.c
@@ -559,7 +559,7 @@ int audit_reset_backlog_wait_time_actual(int fd)
 
 int audit_set_feature(int fd, unsigned feature, unsigned value, unsigned lock)
 {
-#if defined(HAVE_DECL_AUDIT_FEATURE_VERSION)
+#if HAVE_DECL_AUDIT_FEATURE_VERSION == 1
 	int rc;
 	struct audit_features f;
 
@@ -583,7 +583,7 @@ int audit_set_feature(int fd, unsigned feature, unsigned value, unsigned lock)
 
 int audit_request_features(int fd)
 {
-#if defined(HAVE_DECL_AUDIT_FEATURE_VERSION)
+#if HAVE_DECL_AUDIT_FEATURE_VERSION == 1
 	int rc;
 	struct audit_features f;
 
@@ -602,7 +602,7 @@ int audit_request_features(int fd)
 
 extern int  audit_set_loginuid_immutable(int fd)
 {
-#if defined(HAVE_DECL_AUDIT_FEATURE_VERSION)
+#if HAVE_DECL_AUDIT_FEATURE_VERSION == 1
 	return audit_set_feature(fd, AUDIT_FEATURE_LOGINUID_IMMUTABLE, 1, 1);
 #else
 	errno = EINVAL;
diff --git a/lib/netlink.c b/lib/netlink.c
index f7cbeb0..66a1e7c 100644
--- a/lib/netlink.c
+++ b/lib/netlink.c
@@ -147,7 +147,7 @@ static int adjust_reply(struct audit_reply *rep, int len)
 	rep->error    = NULL;
 	rep->signal_info = NULL;
 	rep->conf     = NULL;
-#if defined(HAVE_DECL_AUDIT_FEATURE_VERSION)
+#if HAVE_DECL_AUDIT_FEATURE_VERSION == 1
 	rep->features = NULL;
 #endif
 	if (!NLMSG_OK(rep->nlh, (unsigned int)len)) {
@@ -172,7 +172,7 @@ static int adjust_reply(struct audit_reply *rep, int len)
 		case AUDIT_GET:   
 			rep->status  = NLMSG_DATA(rep->nlh); 
 			break;
-#if defined(HAVE_DECL_AUDIT_FEATURE_VERSION)
+#if HAVE_DECL_AUDIT_FEATURE_VERSION == 1
 		case AUDIT_GET_FEATURE:
 			rep->features =  NLMSG_DATA(rep->nlh);
 			break;
diff --git a/src/auditctl-listing.c b/src/auditctl-listing.c
index 333c832..a5d6bc2 100644
--- a/src/auditctl-listing.c
+++ b/src/auditctl-listing.c
@@ -585,7 +585,7 @@ int audit_print_reply(struct audit_reply *rep, int fd)
 #endif
 			printed = 1;
 			break;
-#if defined(HAVE_DECL_AUDIT_FEATURE_VERSION)
+#if HAVE_DECL_AUDIT_FEATURE_VERSION == 1
 		case AUDIT_GET_FEATURE:
 			{
 			uint32_t mask = AUDIT_FEATURE_TO_MASK(
diff --git a/src/auditctl.c b/src/auditctl.c
index 995b183..ebff6e8 100644
--- a/src/auditctl.c
+++ b/src/auditctl.c
@@ -135,7 +135,7 @@ static void usage(void)
      "    -v                                Version\n"
      "    -w <path>                         Insert watch at <path>\n"
      "    -W <path>                         Remove watch at <path>\n"
-#if defined(HAVE_DECL_AUDIT_FEATURE_VERSION)
+#if HAVE_DECL_AUDIT_FEATURE_VERSION == 1
      "    --loginuid-immutable              Make loginuids unchangeable once set\n"
 #endif
 #if HAVE_DECL_AUDIT_VERSION_BACKLOG_WAIT_TIME == 1 || \
@@ -532,7 +532,7 @@ static int parse_syscall(const char *optarg)
 
 static struct option long_opts[] =
 {
-#if defined(HAVE_DECL_AUDIT_FEATURE_VERSION)
+#if HAVE_DECL_AUDIT_FEATURE_VERSION == 1
   {"loginuid-immutable", 0, NULL, 1},
 #endif
 #if HAVE_DECL_AUDIT_VERSION_BACKLOG_WAIT_TIME == 1 || \
-- 
2.7.4
```

**Comment by stevegrubb** [comment]
Yes, this looks like the right fix. Do you want to submit as a pull request?

**Comment by vigneshoff** [comment]
Hi Steve,

Thanks, Could you push my above patch? or Do I need to raise it as a PR?

**Comment by rgbriggs** [comment]
On 2021-10-01 01:36, vigneshoff wrote:
>    Thanks, Could you push my above patch? or Do I need to raise it as a PR?

Dumb question...  Has it been tested when that macro isn't defined?

**Comment by stevegrubb** [comment]
This makes it match how it's done everywhere else in the audit project. So, if this is wrong, we need to fix it everywhere. Alternatively, other places use ifdef instead of if defined(). Either way, HAVE_DECL_AUDIT_FEATURE_VERSION is different than everywhere else.

**Comment by stevegrubb** [comment]
Vignesh, I applied the patch. Pull requests are easier to apply if you send something in the future. Thanks for the patch!
