### ISSUE TITLE
Resume_logging does not seem to work correctly

### ISSUE THREAD

**Issue by yixiangzhike** [linux-audit/audit-userspace#222]
When my logging is SUSPEND, I give a signal SIGUSR2 to auditd, or execute command "service auditd resume", logging is still SUSPEND. Resume_logging does not work correctly. Whether log_size needs to be reset in function resume_logging()?

auditd.conf
max_log_file_action = SUSPEND

/var/log/audit/audit.log
type=DAEMON_RESUME msg=audit(1635049978.088:971): op=resume-logging auid=0 pid=3881 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 res=success^]AUID="root"

/var/log/message
Oct 24 12:32:58 study auditd[1716]: Audit daemon is attempting to resume logging.
Oct 24 12:32:58 study auditd[1716]: Audit daemon is suspending logging due to logfile size.
Oct 24 12:32:58 study [/bin/bash]: [kill -12 `pidof auditd`] return code=[0], execute success by [root(uid=0)] from [pts/1 (192.168.58.1)]

**Comment by stevegrubb** [comment]
The setting for suspended is to give you a chance to manually intervene and make space available. If you have not done that, then this is what happens. If you want it to automatically fix itself, set it as rotate or keep_logs. Otherwise you are expected to fix it yourself and then resume.
