### ISSUE TITLE
How to use the '- F' parameter of 'auditctl' command to write two or relational conditions in a rule

### ISSUE THREAD

**Issue by dreamtale90** [linux-audit/audit-userspace#226]
For example, I want to monitor the execve behavior of user IDs 1000 and 1001. The following information is found in the man manual.
`-F [n=v | n!=v | n<v | n>v | n<=v | n>=v | n&v | n&=v]`
Therefore, I think it should be written like this, but the result is wrong.
```
0 18:28:11 audispd # auditctl -a always,exit -S execve -F auid=1001|auid=1002 
WARNING - 32/64 bit syscall mismatch, you should specify an arch
0 18:52:14 audispd # auditctl -l
-a always,exit -S execve -F auid=1001
```
I want to know if this usage is supported and how to use it if so.
Thanks in advanced.

**Comment by stevegrubb** [comment]
Fields in the same rule are "anded". To make an "or" you write a new rule. You can group them together by using the same key. Then you can find either by searching on the key.

**Comment by dreamtale90** [comment]
OK, thanks. @stevegrubb
