### ISSUE TITLE
-F exe does not work as expected with containers

### ISSUE THREAD

**Issue by adduali1310** [linux-audit/audit-userspace#227]
When using auditd to allowlist a few noisy events, I make use of the -F exe field. This seems to work as expected on host nodes but when any event occurs inside a container running on the host, the "exe" field does not work as expected.

For example-

-a never,exit -F arch=b64 -S openat -S write -S unlink -S mkdirat -S access  -S execve -F exit=-13 -F exe=/bin/bash (Allowlist Rule)
-a always,exit -F arch=b64 -S all -F exit=-13 -k access-denied (Noisy Rule)

If I perform any action on the host, where the exe=/bin/bash and permission is denied , the event is allowlisted as expected and noting gets logged.

But if I perform the same action in a Docker container, where exe=/bin/bash and permission is denied, then the event is not allowlisted  and is logged eventhough all the fields in the audit.log for the event are in the allowlist.

**Comment by rgbriggs** [comment]
On 2021-11-11 16:24, adduali1310 wrote:
> When using auditd to allowlist a few noisy events, I make use of the -F exe field. This seems to work as expected on host nodes but when any event occurs inside a container, the "exe" field does not work as expected.

I'm guessing the likely cause is that the container and the host are using different mount namespaces.  The result being that the watched device/inode differs from the one being used in the container.

**Comment by adduali1310** [comment]
Aah...that would make sense and explains why the -F exe option does not work.

Any other options that we can use to allowlist such events? I thought of adding this to the allowlist -F auid=-1 and remove the -F exe part, but this would even allowlist other executables and events that are started by a daemon and will not be specifically limited to the executable we want which is theuse case here.

**Comment by stevegrubb** [comment]
I think we can close this. The audit subsystem is not yet container aware. There are kernel and user space issues that can be monitored for progress.
