### ISSUE TITLE
dnf symlink used in 44-installers.rule 

### ISSUE THREAD

**Issue by The-Mule** [linux-audit/audit-userspace#230]
Sample rules file 44-installers.rules uses -F path=/usr/bin/dnf but that is just a symlink to /usr/bin/dnf-3 (in both Fedora and RHEL) and since links are not followed this rule won't catch anything. Also, it might be good to add 'rpm' to the list.

https://github.com/linux-audit/audit-userspace/blob/f3cbdb30238f453fcbed9d530ff6421b6b690cad/rules/44-installers.rules#L3

**Comment by stevegrubb** [comment]
Thanks for reporting the issue. Commit 7c4e424 should fix this. Rpm was intentionally left off because it generates it's own audit events.
