### ISSUE TITLE
BUG: missing or undiscoverable security policy

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-userspace#232]
There should be a well defined policy for handling serious bugs and security vulnerabilities in the code so that security researchers and others know how to report sensitive issues to the project.  There may already be a policy in place for this project, but I couldn't seem to find a reference to it in this repository; making it a bit more discoverable would be a good thing IMO.

For reference here is the GH documentation on security policies:

* https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

... as well as a simple (if imperfect) example of the security policy we use for libseccomp:

* https://github.com/seccomp/libseccomp/security/policy

**Comment by stevegrubb** [comment]
@pcmoore is there anything specifically that you would like to see in the security policy? I'm inclined to make it very short.

**Comment by pcmoore** [comment]
I think the key piece of information to have in the doc is a pointer to the responsible party to contact in case a security issue is found.  The other stuff is nice to have so the proper expectations are set, but likely not critical.

**Comment by stevegrubb** [comment]
OK, Security policy has been committed.

**Comment by pcmoore** [comment]
Thanks.
