### ISSUE TITLE
AVC event missing name of anonymous inode class

### ISSUE THREAD

**Issue by cgzones** [linux-audit/audit-userspace#233]
While testing a patch regarding memfd_secret(2) and anonymous inodes I noticed the `name of the anonymous inode class` of the LSM hook `inode_init_security_anon` (added in https://github.com/torvalds/linux/commit/215b674b84dd052098fe6389e32a5afaff8b4d56) is not included in the AVC event (in this case it would be `[secretmem]`):

```
type=PROCTITLE msg=audit(01/21/22 15:31:57.731:16139) : proctitle=../../mem_secret/test
type=SYSCALL msg=audit(01/21/22 15:31:57.731:16139) : arch=x86_64 syscall=memfd_secret success=no exit=EACCES(Permission denied) a0=0x0 a1=0x7fc133049854 a2=0x0 a3=0x10007fff8000 items=0 ppid=592 pid=1222 auid=root uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts1 ses=1 comm=test exe=/root/workspace/mem_secret/test subj=root:sysadm_r:sysadm_t:s0-s0:c0.c1023 key=(null)
type=AVC msg=audit(01/21/22 15:31:57.731:16139) : avc:  denied  { create } for  pid=1222 comm=test dev="secretmem" ino=4998 scontext=root:sysadm_r:sysadm_t:s0-s0:c0.c1023 tcontext=root:sysadm_r:sysadm_t:s0 tclass=anon_inode permissive=0
```

This name is important for SELinux policy writers, as it is essential for the name based type transition for anonymous inodes (see commit description of https://github.com/torvalds/linux/commit/29cd6591ab6fee3125ea5c1bf350f5013bc615e1 using `[userfaultfd]` as an object name for the transition to a private type).

/cc @pcmoore

**Comment by stevegrubb** [comment]
This sounds more like a kernel problem - specifically the selinux subsystem. Might also be helpful to state the kernel that has the problem. Thanks.

**Comment by cgzones** [comment]
It was a custom build vanilla Linux 5.16.0 with some development patches (but no audit or inode_init_security_anon implementation related ones) for Debian sid with auditd 3.0.6.

**Comment by cgzones** [comment]
The audit data seems to be set at https://github.com/torvalds/linux/blob/49d766f3a0e49624c4cf83909d56c68164e7c545/security/selinux/hooks.c#L3029-L3030, but probably the dentry has on the one hand no name (https://github.com/torvalds/linux/blob/49d766f3a0e49624c4cf83909d56c68164e7c545/security/lsm_audit.c#L296-L301) and on the other hand I am interested in the anonymous class name.

**Comment by cgzones** [comment]
Resolved via https://github.com/SELinuxProject/selinux-kernel/commit/c29722fad4aabbf6bb841b8f058f858ec911df56
