### ISSUE TITLE
Man-page for auditd.cron does not exist

### ISSUE THREAD

**Issue by miztake** [linux-audit/audit-userspace#249]
Attempting to rotate audit.log based on time instead of size cannot be achieved with auditd's log rotation.
Because auditd's log rotation is size-based.
For time-based rotation, auditd.cron must be run with logrotate.
However, there is no man-page for auditd.cron.

**Comment by stevegrubb** [comment]
That's true. And we don't install the file where it is automatically used. Instead, it's made available in case someone might want it or wants to do something similar but different. I kind of feel like any documentation might want to be in the file itself. So, that if anyone decides to install the file, they can read about it in the file. But for everyone else who doesn't elect to install it, it's not cluttering up the man pages.

**Comment by stevegrubb** [comment]
I reviewed the auditd.cron file. I modified the documentation in it. I think it is enough. Also the cron job does not use logrotate. It directly tells auditd it should rotate the logs.

**Comment by stevegrubb** [comment]
I think this issue can be closed out. Thanks for reporting it!
