### ISSUE TITLE
A possible locking issue(e.g., deadlock)

### ISSUE THREAD

**Issue by ryancaicse** [linux-audit/audit-userspace#258]
Hi, lock `flush_lock` is not released before Line 212. Should it be a bug?
https://github.com/linux-audit/audit-userspace/blob/770e4f538103f8a055f46c04a9e2514f88f175c3/src/auditd-event.c#L204-L215

**Comment by stevegrubb** [comment]
Thanks for noticing. I tried to test this with the thread sanitizer and it did not detect this issue. But I made the change anyways. Commit f7df667 should address this issue.

**Comment by ryancaicse** [comment]
Thanks!
