### ISSUE TITLE
[python-audit] error: cast specifies array type

### ISSUE THREAD

**Issue by tallero** [linux-audit/audit-userspace#265]
I'm experiencing [this same bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010289) when building on arch, too.

**Comment by stevegrubb** [comment]
This is a duplicate of issue 236 and 252. The later mentions PR https://github.com/linux-audit/audit-userspace/pull/253
Also, see https://listman.redhat.com/archives/linux-audit/2022-February/018832.html

**Comment by tallero** [comment]
I forgot to mention I'm on 2.8.5. I don't remember if it was because I wanted python2 support.

**Comment by stevegrubb** [comment]
Looking at this and PR #253 again, the python setter is used to add a path to a watch rule.

**Comment by stevegrubb** [comment]
I want to leave some bread crumbs here. There is PR #253 which offers probably best solution but loses the ability to create watches via python. And there is the swig issue that mentions this https://github.com/swig/swig/issues/1699

**Comment by tallero** [comment]
@stevegrubb

ok, so for now arch [uses](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python2-audit#n42) the third in https://github.com/swig/swig/issues/1699#issuecomment-1193307710.

**Comment by stevegrubb** [comment]
I won't have any time for the foreseeable future to rewrite audit bindings. Commit 1ca7e2b selects swig option 3.
