### ISSUE TITLE
audispd(8) man page referenced but does not exist

### ISSUE THREAD

**Issue by adelton** [linux-audit/audit-userspace#267]
In https://github.com/linux-audit/audit-userspace/blob/master/audisp/plugins/remote/audisp-remote.conf.5,
```
.SH "SEE ALSO"
.BR audispd (8),
```
is used.

In https://github.com/linux-audit/audit-userspace/blob/master/audisp/plugins/zos-remote/audispd-zos-remote.conf,
```
# audit dispatcher plugin - See audispd(8)
```
is used.

However, that audispd(8) man page does not seem to exist anywhere.

**Comment by stevegrubb** [comment]
Thanks. Commit 9c74da5 should fix this.
