### ISSUE TITLE
Auditd Service not starting on Podman Container

### ISSUE THREAD

**Issue by KyalSmith** [linux-audit/audit-userspace#268]
I am using ansible molecule with podman to automate auditd testing.
The ansible files can be found here:
[https://github.com/robertdebock/ansible-role-auditd](url)

The only thing I have modified in the files is the molecule.yml file to use podman instead of docker.

When running `molecule converge` the last task called "start and enable auditd" is failing.

It says The output from the journalctl on the container says "Operation not permitted"
Command:
`journalctl -xeu auditd.service`

Output:
Jul 20 08:38:28 auditd-fedora-latest systemd[1]: Starting auditd.service - Security Auditing Service...
░░ Subject: A start job for unit auditd.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit auditd.service has begun execution.
░░
░░ The job identifier is 119.
Jul 20 08:38:28 auditd-fedora-latest auditd[295]: The disp_qos option is deprecated - line 15
Jul 20 08:38:28 auditd-fedora-latest auditd[295]: The dispatcher option is deprecated - line 16
Jul 20 08:38:28 auditd-fedora-latest auditd[295]: Cannot change priority (Operation not permitted)
Jul 20 08:38:28 auditd-fedora-latest auditd[295]: The audit daemon is exiting.
Jul 20 08:38:28 auditd-fedora-latest systemd[1]: auditd.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ An ExecStart= process belonging to unit auditd.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Jul 20 08:38:28 auditd-fedora-latest systemd[1]: auditd.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ The unit auditd.service has entered the 'failed' state with result 'exit-code'.
Jul 20 08:38:28 auditd-fedora-latest systemd[1]: Failed to start auditd.service - Security Auditing Service.

Environment:
    Control node OS: Ubuntu 22.04
    Control node Ansible version: 2.13.0
    Managed node OS: Fedora Linux 36

I read an older stackoverflow question from 2018 where the issue seemed that auditd is not supported on containers due to namespace issues.
Is this still the case?

**Comment by rgbriggs** [comment]
On 2022-07-20 03:35, KyalSmith wrote:
> Is this due to the fact that running auditd within a container is not supported?

Yes/no.  It all depends in which kernel namespace(s) it is attempted to
being started.  At this point, auditd can only run in the initial pid
and user namespaces.  So if your container infrastructure is trying to
start it in a child pid or user namespace, it will be refused by the
kernel.  See the kernel function audit_netlink_ok().  This answer may
not be directly helpful, but this is one likely root cause.

**Comment by KyalSmith** [comment]
Hi,
Sorry I'm not much of a C dev(not to mention kernel development).
I had a look and I could be wrong but you referring to this section of code:
`case AUDIT_MAKE_EQUIV:
		/* Only support auditd and auditctl in initial pid namespace
		 * for now. */
		if (task_active_pid_ns(current) != &init_pid_ns)
			return -EPERM;`


So from what I understand so far to resolve this, is to find a way to run the container software within kernel space?
Are there other options regarding this?
Please forgive me my ignorance, this is uncharted waters for me.

**Comment by rgbriggs** [comment]
On 2022-07-21 01:53, KyalSmith wrote:
> 		if (task_active_pid_ns(current) != &init_pid_ns)
> 			return -EPERM;`

Yes, and:

	if (current_user_ns() != &init_user_ns)
		return -ECONNREFUSED;

> So from what I understand so far to resolve this, is to find a way to run the container software within kernel space?

Within kernel *initial* pid and user namespaces, yes.

> Are there other options regarding this?

Not yet, but there is work planned for the future to try to accomodate this:
	https://github.com/linux-audit/audit-kernel/issues
Related issues include 68, 75, 79, 90, 91, 92, 93...

**Comment by KyalSmith** [comment]
Hi again,

Thanks much for the help. I'll have a look about running the podman instance via the init pid and see.
