### ISSUE TITLE
statically link auditd 

### ISSUE THREAD

**Issue by motazreda** [linux-audit/audit-userspace#275]
Hi,

i need to build and statically link auditd project to use as a standalone binary.

i tried the following compiler options
```bashsudo LDFLAGS="-lm -lc -lgcc -lc -static -static-libgcc" CFLAGS="-lm -lc -lgcc -lc -static -static-libgcc" ./configure```

it compiles successfully but the audtd still dynamically linked.

ldd command shows that after the above command and then make:

```bash ldd src/auditd
	linux-vdso.so.1 (0x00007fffc3beb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc3c760f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc3c73e7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc3c777c000)
```
now it did static linking the libraries that came with auditd but did not static link libc and libm.

Thanks

**Comment by stevegrubb** [comment]
./configure --enable-static --disable-shared --without-python --without-python3

But I get the same results. I think static libraries for all dependencies need to be installed or this is what you get. If they are available and it's not doing a static link, it might be a limitation of autotools. I see people complaining of the same thing in other places.

**Comment by stevegrubb** [comment]
Thanks for reporting this. I think this is an autotools issue. I don't think there is anything actionable for audit-userspace.
