### ISSUE TITLE
`auditctl -R` always prepends rules instead of replacing the list of rules

### ISSUE THREAD

**Issue by wpyoga** [linux-audit/audit-userspace#279]
When `auditctl -R rulesfile` is executed, the rules inside the file is always prepended to the current list of rules. The list of rules is not replaced. `auditctl` itself returns success. An example of this usage is when `augenrules --load` is executed.

Is this intended behavior? I had thought (intuitively) that the `-R` option should in effect reload all the rules, so all the rules are removed and replaced by the ones defined in the rules file.

As you can see below:

```sh
[william@t14 ~]$ echo '-A exclude,always' > test-audit.rules
[william@t14 ~]$ echo '-A exclude,never' > test-audit-2.rules
[william@t14 ~]$ sudo chown root test-audit.rules test-audit-2.rules 
[william@t14 ~]$ sudo auditctl -D ; echo $? ; sudo auditctl -l
No rules
0
No rules
[william@t14 ~]$ sudo auditctl -R test-audit.rules ; echo $? ; sudo auditctl -l
0
-a always,exclude
[william@t14 ~]$ sudo auditctl -R test-audit.rules ; echo $? ; sudo auditctl -l
0
-a always,exclude
-a always,exclude
[william@t14 ~]$ sudo auditctl -R test-audit-2.rules ; echo $? ; sudo auditctl -l
0
-a never,exclude
-a always,exclude
-a always,exclude
```

**Comment by stevegrubb** [comment]
It is up to the rules to decide what to do. auditctl simply carries out the command. If you want to reload rules, start with '-D' which deletes all rules. This is why 10-base-config.rules start by deleting previous rules. I think this issue can be closed.

**Comment by stevegrubb** [comment]
I don't think there is anything to fix here. If there is, please feel free to reopen.

**Comment by wpyoga** [comment]
I have re-read the documentation, and I see now what you mean. I've submitted PR #292 to improve the documentation.

Sorry for the delay in my response, and thank you for explaining the mechanism.
