### ISSUE TITLE
`auditctl -R` silently fails if rules file is not owned by root or is world-readable

### ISSUE THREAD

**Issue by wpyoga** [linux-audit/audit-userspace#280]
So if we run `auditctl -R rulesfile` and the rules file is not owned by root, or is world-readable, then the operation fails with an exit status of `1` (error), but there is no error message printed to stderr. Is this by design?

If so, I would propose that when this happens, an error message is printed to stderr, maybe something like this:

```
The rules file provided to -R must be owned by root, and must not be world-writable.
```

You can see the current behavior below:

```sh
[william@t14 ~]$ echo '-A exclude,always' > test-audit.rules
[william@t14 ~]$ ls -l test-audit.rules 
-rw-r--r-- 1 william william 18 Sep 16 13:59 test-audit.rules
[william@t14 ~]$ sudo auditctl -D ; echo $? ; sudo auditctl -l
No rules
0
No rules
[william@t14 ~]$ sudo auditctl -R test-audit.rules ; echo $? ; sudo auditctl -l
1
No rules
[william@t14 ~]$ echo '-A exclude,never' > test-audit-2.rules
[william@t14 ~]$ sudo chown root test-audit-2.rules 
[william@t14 ~]$ ls -l test-audit-2.rules 
-rw-r--r-- 1 root william 17 Sep 16 14:00 test-audit-2.rules
[william@t14 ~]$ sudo auditctl -D ; echo $? ; sudo auditctl -l
No rules
0
No rules
[william@t14 ~]$ sudo auditctl -R test-audit-2.rules ; echo $? ; sudo auditctl -l
0
-a never,exclude
[william@t14 ~]$ echo '-A always,exclude' > test-audit-3.rules
[william@t14 ~]$ sudo chown root test-audit-3.rules 
[william@t14 ~]$ sudo chmod 666 test-audit-3.rules 
[william@t14 ~]$ ls -l test-audit-3.rules 
-rw-rw-rw- 1 root william 18 Sep 16 14:02 test-audit-3.rules
[william@t14 ~]$ sudo auditctl -D ; echo $? ; sudo auditctl -l
No rules
0
No rules
[william@t14 ~]$ sudo auditctl -R test-audit-3.rules ; echo $? ; sudo auditctl -l
1
No rules
```

**Comment by wpyoga** [comment]
Additionally, a few things I noticed:
- The rules file is allowed to be world-readable. Is this intentional? Because the rules in `/etc/audit` are not world-readable.
- The group ownership of the rules file is not checked -- is this also intentional?

I can contribute patches, if you want.

**Comment by stevegrubb** [comment]
Long ago people were annoyed by auditctl writing to stderr. It was suggested to syslog the occurrence since auditctl only runs during boot.

**Comment by RichieB2B** [comment]
@stevegrubb Thanks, that is an explanation but not really an excuse. The error behaviour of `auditctl` is very inconsistent. It will write to stderr for `-w` failures but not for `-R` failures. 

```
# date
Tue May 30 09:04:01 UTC 2023
# auditctl -R /etc/audit/audit.rules 
# echo $?
0
# grep audit /var/log/messages |tail -1
May 30 09:04:02 lvm-test auditctl[2308]: The audit system is in immutable mode, no rule changes allowed
# date
Tue May 30 09:04:56 UTC 2023
# auditctl -w  /tmp/test  -p war -k monitor-test
The audit system is in immutable mode, no rule changes allowed
# echo $?
0
# grep audit /var/log/messages |tail -1
May 30 09:04:02 lvm-test auditctl[2308]: The audit system is in immutable mode, no rule changes allowed
```
At the very lease I expect it to set an error code when it fails.

**Comment by stevegrubb** [comment]
The -R option is used during system init so we want all of that to go to syslog. If we do both, systemd puts both in the logs. The -w command should be at the command line.  I fixed the return code for immutable mode with commit 55050bc. Thanks for pointing that out.

**Comment by RichieB2B** [comment]
Thanks for that fix. Please consider writing to stderr instead of syslog for `-R` failures. This will make interactive use of `auditctl` much more friendly. As you pointed out the messages on strerr during boot will still end up in the journal and/or syslog.

**Comment by stevegrubb** [comment]
Might be easier to just not be too paranoid about the file. Nothing will happen unless you have CAP_AUDIT_CONTROL.

**Comment by stevegrubb** [comment]
Commit 3bbe0ab should make this better. Thanks for reporting the issue.
