### ISSUE TITLE
Allow checking for `success` field with `exclude` rule?

### ISSUE THREAD

**Issue by wpyoga** [linux-audit/audit-userspace#281]
In my use case, I want to filter `sudo` events which are successful. So if a `sudo` call is successful it should be filtered, but not if it failed.

Currently, I cannot do it:

```sh
$ sudo auditctl -A exclude,always -F exe=/usr/bin/sudo -F success=1
Only msgtype, *uid, *gid, pid, and subj* fields can be used with exclude filter
```

So... I'm proposing a feature to allow the `success` field to be checked when using the `exclude` rule, and I think this would also be useful to others.

Please le me know if this is OK, and I can contribute a patch for this.

**Comment by stevegrubb** [comment]
I think this was recently fixed. It should be in the next release.
