### ISSUE TITLE
RFC: audit fields for USER_AVC records

### ISSUE THREAD

**Issue by cgzones** [linux-audit/audit-userspace#283]
For applications processing SELinux denials reports, like SETroubleShoot, it would be nice to have some common fields in USER_AVC records about the underlying subject to improve reasoning about the origin of the denial.

AVC records from the kernel contain a comm field and are commonly accompanied by a PROCTITLE and SYSCALL record containing the full command line and the executable path:

```
type=PROCTITLE msg=audit(08/06/22 17:34:34.458:201) : proctitle=/lib/systemd/systemd-networkd-wait-online -q --timeout=30
type=SYSCALL msg=audit(08/06/22 17:34:34.458:201) : arch=x86_64 syscall=fstatfs success=no exit=EACCES(Permission denied) a0=0x3 a1=0x7fff69cd7820 a2=0x0 a3=0x0 items=0 ppid=2939 pid=2943 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=systemd-network exe=/usr/lib/systemd/systemd-networkd-wait-online subj=system_u:system_r:apt_helper_t:s0 key=(null)
type=AVC msg=audit(08/06/22 17:34:34.458:201) : avc:  denied  { getattr } for  pid=2943 comm=systemd-network name=/ dev="proc" ino=1 scontext=system_u:system_r:apt_helper_t:s0 tcontext=system_u:object_r:proc_t:s0 tclass=filesystem permissive=0
```

USER_AVC records currently only include a standard exe field, which contains the path to the executable of the userspace object manager, not the underlying subject, and are missing the pid, exe, comm and cmdline of the subject and (in case of systemd) duplicate the auid and uid fields:

```
# dbus-broker
type=USER_AVC msg=audit(22/09/22 16:58:47.569:313) : pid=789 uid=dbus auid=unset ses=unset subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  granted  { send_msg } for  scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tclass=dbus  exe=/usr/bin/dbus-broker sauid=dbus hostname=? addr=? terminal=?'

# systemd
type=USER_AVC msg=audit(22/09/22 15:35:47.847:132) : pid=1 uid=root auid=unset ses=unset subj=system_u:system_r:init_t:s0 msg='avc:  granted  { reload } for auid=unset uid=root gid=root cmdline="" function="method_reload" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=system_u:system_r:init_t:s0 tclass=system exe=/usr/lib/systemd/systemd sauid=root hostname=? addr=? terminal=?'
```

I'd like to propose userspace object managers *should* provide the following fields of the subject: `pid`, `auid`, `uid`, `gid`, `ses/sid`, `exe`, `comm` and `cmdline`.
Currently the following fields exit mentioning *"the analyzed process"*: `sauid`, `suid`, `sgid`.
In the context of userspace object managers is the process, whose access is checked, the *subject* or *"the analyzed process"*?
Thus should the information about it be supplied in fields with a prefix of `s` (like `sauid`) or `subj` (like `subj_auid`)?

Also the documentation of `audit_log_user_avc_message(3)` could be improved whether the parameters hostname, addr, tty and uid refer to the process issuing the audit message or the process the message is about (e.g. dbus-broker hardcodes uid to `getuid(3)` and systemd to `0`).

/cc @bachradsusi

**Comment by stevegrubb** [comment]
The thing is that you can't always trust the sending process. What if it's compromised? There are 2 sets of fields in USER_AVC's, the ones from the kernel which can be trusted and the ones that are sent. This is why some fields are prefixed with a 's'. It is less trustworthy. I might be able to add the comm field, but we can't get anything else because it's not a syscall event or the kernel should be supplying it but isn't.

**Comment by cgzones** [comment]
> The thing is that you can't always trust the sending process. What if it's compromised? There are 2 sets of fields in USER_AVC's, the ones from the kernel which can be trusted and the ones that are sent.

Nothing in an USER_AVC record comes directly from the kernel; it's a combination of libselinux (alterable by a compromised object manager) (https://github.com/SELinuxProject/selinux/blob/02bdee369c0b596927dec9ee64bb00f09856bed9/libselinux/src/avc.c#L692-L731), object manager (e.g. systemd: https://github.com/systemd/systemd/blob/d9e1cb288f9f2b76b281c163070a3083231b0792/src/core/selinux-access.c#L41-L69) and libaudit (audit_log_user_avc_message(3)).
So the object managers are already trusted since they provide the two most important fields of an USER_AVC record: scontext and tcontext.

For reasoning about the specific cause of an userspace denial I'd like to have some extended information, e.g. (spid, suid, sgid, sexe, scmdline):

```
type=USER_AVC msg=audit(22/09/22 16:58:47.569:313) : pid=789 uid=dbus auid=unset ses=unset subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  granted  { send_msg } for spid=4200 suid=root sgid=root sexe="/usr/bin/networkctl" scmdline="networkctl list" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tclass=dbus  exe=/usr/bin/dbus-broker sauid=root hostname=? addr=? terminal=?'
```

**Comment by cgzones** [comment]
Draft of systemd update: https://github.com/systemd/systemd/pull/25264

**Comment by stevegrubb** [comment]
Hello, I am cleaning up old issues. Where are we at in this discussion? Is there anything else to discuss or can we close this?

**Comment by stevegrubb** [comment]
Thanks for raising the issue. If you need any more discussion, please open a new issue or better, take it to the mail list.
