### ISSUE TITLE
Unable to add Key to audit rule, using audit_rule_fieldpair_data

### ISSUE THREAD

**Issue by anurag19** [linux-audit/audit-userspace#285]
Hello All,

I am trying to generate an audit rule with specified key, but the function call to audit_rule_fieldpair_data fails with a return value of -19.

I have added a system call using the audit_rule_syscallbyname_data function in the same rule.

Can you please help here? I am unable to understand why it is saying "**Key field needs a watch, syscall or exe path given prior to it**" even though a system call has been added as a part of the rule.

Sample code:

```

#include <stdio.h>
#include <libaudit.h>

int main()
{
    int fd = audit_open();
    struct audit_rule_data *rule = new audit_rule_data();
    audit_rule_syscallbyname_data(rule, "socket");

    char arch[] = "arch=b64";
    char pair[] = "a0=0xA";
    char success[] = "success=1";
    char key[] = "key=abcd";
    audit_rule_fieldpair_data(&rule, arch, 0);
    audit_rule_fieldpair_data(&rule, pair, 0);
    auto keyret = audit_rule_fieldpair_data(&rule, key, 0);
   
     
    printf("Result of adding key: %d", keyret);

    audit_close(fd);

}

```
**NOTE:** Please refer to the [Reporting Bug and Requesting Features](https://github.com/linux-audit/audit-documentation/wiki/Reporting-Bugs-and-Requesting-Features) wiki page before creating any new GitHub issues.

**Comment by stevegrubb** [comment]
2 things...your program should be restructured like this:
    char arch[] = "arch=b64";
    char pair[] = "a0=0xA";
    char success[] = "success=1";
    char key[] = "key=abcd";
    struct audit_rule_data *rule = audit_rule_create_data();
    rule->action = AUDIT_ALWAYS;
    rule->flags = AUDIT_FILTER_EXIT;
    audit_rule_fieldpair_data(&rule, arch, 0);
    audit_rule_syscallbyname_data(rule, "socket");
    audit_rule_fieldpair_data(&rule, pair, 0);

And there is a missing initializer in audit_rule_syscallbyname_data that is set in auditctl but is private. A commit was just applied which will fix your issue.

**Comment by anurag19** [comment]
Thanks Steve, I saw that the initialiser was not being set. I was hoping to send a commit tomorrow.

**Comment by stevegrubb** [comment]
I'm close to finishing the io_uring support. Once that is finished, 3.1 will be released. So, maybe later in the week?

**Comment by rgbriggs** [comment]
On 2022-12-06 06:51, Steve Grubb wrote:
> I'm close to finishing the io_uring support. Once that is finished, 3.1 will be released. So, maybe later in the week?

I hope it uses -U to define the iouring ops for the filter rather than
re-mis-using the -S parameter to do so, conflating with syscall names
that don't match up 1:1.  Like what was done in the code I had submitted
a while back.

**Comment by rgbriggs** [comment]
On 2022-12-06 13:11, Richard Guy Briggs wrote:
> On 2022-12-06 06:51, Steve Grubb wrote:
> > I'm close to finishing the io_uring support. Once that is finished, 3.1 will be released. So, maybe later in the week?
> 
> I hope it uses -U to define the iouring ops for the filter rather than
> re-mis-using the -S parameter to do so, conflating with syscall names
> that don't match up 1:1.  Like what was done in the code I had submitted
> a while back.

The series is here:
	https://listman.redhat.com/archives/linux-audit/2021-October/018486.html

-U patch here:
	https://listman.redhat.com/archives/linux-audit/2021-October/018488.html

uring op names here:
	https://listman.redhat.com/archives/linux-audit/2021-October/018489.html

**Comment by stevegrubb** [comment]
Closing this. Next release will have the fix.
