### ISSUE TITLE
Auparse does not parse event until next arrives

### ISSUE THREAD

**Issue by tperka-catalogicsoftware** [linux-audit/audit-userspace#286]
Hello, 
I've encountered a problem with real-time parsing of events through `auparse` I've tried both `AUSOURCE_FEED` and `AUSOURCE_DESCRIPTOR` as sources for `auparse_init`. In both cases I've used a `AF_UNIX` socket to communicate with audit. In first case I've retrieved text data and fed it to parser using `auparse_feed` and in second case I've directly passed file descriptor corresponding to client socket. In both cases events appear in logs without any delay, but:
* In first case the callback won't be invoked until next event arrives, despite all needed data being passed by socket - I've used debugger to look into it, the whole event with EOE record is received instantly but callback is not called until next event is fed into parser
* In second case calling `auparse_next_event()` will return non-success until next event arrives.

Interestingly the issue does not occur on Ubuntu 20.04 which utilizes audit 2.8.5-2, which is really weird. Any ideas why it could be or fixes coming soon?

OSes: CentOS/RHEL 7 and 8, Alma/RHEL 9
audit versions: 2.8.5-4.el7,  3.0.7-4.el8, 3.0.7-103.el9

audit rules:
```
-D
-b 8192
-f 1
-w / -p w -k <tag>
--backlog_wait_time 0
-e 1
```

audit plugin config:

```
active = yes
direction = out
path = builtin_af_unix
type = builtin
args = 0640 <path_to_socket>
format = string
```

**Comment by stevegrubb** [comment]
Auparse tries to guarantee the order of events. Events can be out of order upon reception or even interlaced with another. Userspace has to serialize the events. There have been several functions added to help fix this. I would point to this event loop as being about state of the art:

https://github.com/linux-audit/audit-userspace/blob/master/audisp/plugins/ids/ids.c#L239

**Comment by stevegrubb** [comment]
Also, look in the same program in the link above for a call to auparse_set_eoe_timeout(). The default is 3 and it always depends on arrival of new events since auparse does not set any kind of timer which might interfere with the program using auparse. Instead, the calling program can manage the time and force aging of events as demonstrated in the ids main loop above.

**Comment by stevegrubb** [comment]
I don't see any issue that I can fix in this report. The use of the aging functions and eoe_timeout should keep the events flowing. The example pointed to should illustrate their usage. Can we close this issue?

**Comment by stevegrubb** [comment]
Closing. If you feel there is more to discuss, please feel free to reopen.
