### ISSUE TITLE
Auparse missing CWD record despite it being in logs

### ISSUE THREAD

**Issue by tperka-catalogicsoftware** [linux-audit/audit-userspace#287]
Hello,
I've got issue on the same setup as described in https://github.com/linux-audit/audit-userspace/issues/286, but this time it is about skipping CWD record on some events (very rarely, but it's breaking my program). Despite what audit documentation is saying, some filesystem-related events (my rules are set to only track filesystem events) are missing CWD record in auparse. Here is example of `auparse_get_record_text_(au)` output after executing `auparse_goto_record_num(au, 1)` which I would expect to be CWD record:
`node=<node> type=PATH msg=audit(70510548.973:58710988): item=0...`

Despite logs looking like this (event IDs match):

```
type=SYSCALL msg=audit(1670510548.973:58710988): arch=c000003e syscall=2 success=yes exit=3 ...
type=CWD msg=audit(1670510548.973:58710988):  cwd=<cwd>
type=PATH msg=audit(1670510548.973:58710988): item=0 name=<the same as cwd> ... objtype=PARENT
type=PATH msg=audit(1670510548.973:58710988): item=1 name=<filename> ... objtype=NORMAL
type=PROCTITLE msg=audit(1670510548.973:58710988): proctitle=707974686F6E33006D6E5F656E74726F70792E7079
```
As a temporary fix - can the first PATH event (of type PARENT) be used reliably as CWD to obtain absolute paths?

**Comment by stevegrubb** [comment]
I don't know why it would skip CWD records unless they are malformed. It is not designed to do that.

**Comment by stevegrubb** [comment]
If you want to build a path to the object, you can use the PARENT object. It may or may not be the CWD. 

If  you can reliably reproduce the issue, I can look into it. No record should be missing.

**Comment by tperka-catalogicsoftware** [comment]
It's hard to call it `reliable` but in burst of events (~30 000 in one minute) it skips CWD for 2 or 3 events, causing my parsing program to break

**Comment by stevegrubb** [comment]
Is there anything about those that are skipped that stands out?

**Comment by stevegrubb** [comment]
One other thing, auparse_state_t returned by auparse_init is not multithread safe. I should probably add that to the man page.

**Comment by stevegrubb** [comment]
Cleaning up old issues. Is there any new information to consider? I have not run across and code that has been bug fixed since the last discussion that might have a bearing on this. Documentation was added about auparse_state_t not being multi-thread safe. If there is nothing else to discuss, I will close this out in a few days.

**Comment by stevegrubb** [comment]
Thanks for the report. I have no idea how it could occasionally lose a record. I'll keep an eye out for this, though.

**Comment by stevegrubb** [comment]
I just run across something and I am sure this is the problem. If you get a SE Linux AVC that involves an af_unix socket, you will get a PATH record but no CWD. SE Linux has it's own way of extracting information into records and they do not make CWD records.

I'll leave this open for a few days in case anyone else was interested in the resolution.
