### ISSUE TITLE
auditctl -w filename -p wa Bug?

### ISSUE THREAD

**Issue by itaysnir** [linux-audit/audit-userspace#289]
Hey,

Lately I've been playing with `auditctl`, and it seems like recording writes to files doesn't always works. 
I've executed the following code:

```bash
touch audit_test
sudo auditctl -w /home/itay/Documents/audit_test -p wa -k worked
echo "AAAA" >> /home/itay/Documents/audit_test
ausearch -f audit_test
```

However no record is being generated. 
This is my only loaded auditctl rule (`auditctl -l`):

```bash
-w /home/itay/Documents/audit_test -p wa -k worked
```

And i have auditd running (`ps -fade | grep audit`) :

```bash
root          39       2  0 06:04 ?        00:00:00 [kauditd]
root        2521       1  0 06:05 ?        00:00:00 /sbin/auditd
```

Note that file reads (via `cat audit_test`) do work as expected. 

According to the manual page, audit actually monitors file open syscall (with write permissions), instead of monitoring direct writes. 
I assumed it might be related to my issue. 
Therefore, I've assigned the following rule, to monitor write syscalls explicitly:

```bash
auditctl -a always,exit -F arch=b64 -S write -F path=/home/itay/Documents/audit_test -k worked
```

Upon writting to the file, once again, no logs were generated. 

I can verify that indeed `echo` triggered a write syscall that was issued on `audit_test`, via `strace`:
```bash
...
openat(AT_FDCWD, "audit_test", O_WRONLY|O_CREAT|O_APPEND, 0666) = 3
fcntl(1, F_GETFD)                       = 0
fcntl(1, F_DUPFD, 10)                   = 10
fcntl(1, F_GETFD)                       = 0
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
dup2(3, 1)                              = 1
close(3)
...
write(1, "AAAA\n", 5)                  = 5
```

However, by analyzing the strace output, i think the root cause of the problem is due to the output being written to stdout, and dup'ed towards the file. 

In case that is indeed the problem - how may i record such implicit writes? (See EDIT for a hacky solution i found)
If i cannot, can we add a support for these cases?
An alternative solution, is to have an optional flag for auditing `write` of a file explicitly, not only `open` with write permissions.. as it misses many cases. 

Finally - why isn't the logging works, as we clearly see `openat` is being issued on the watched file, with write permissions..

EDIT:
I found a hacky solution to my problem, but i really hate it. 
We can add a syscall rule, based on the `openat` or `open` syscalls, and filtering the argument `a2` to contain a mask of a write bit. 
Only in this case, records do reported whenever a file is being written to. 

Thank You,
Itay

**Comment by stevegrubb** [comment]
The perm field causes a syscall lookup to determine what syscalls are applicable. This is done in the kernel. I don't know what kernel you are using. There have been some problems in older kernels. But this is working fine on Fedora 36 with the 6.0.12 kernel.

**Comment by itaysnir** [comment]
> The perm field causes a syscall lookup to determine what syscalls are applicable. This is done in the kernel. I don't know what kernel you are using. There have been some problems in older kernels. But this is working fine on Fedora 36 with the 6.0.12 kernel.

Thank you for your quick answer.

I've been using an Ubuntu-22.04 5.15 kernel.
Out of curiosity, I've done the same test on a vanilla 6.1.0 kernel I've freshly compiled - and everything works fine. 
So this is indeed some old kernel bug. 

Thank you

**Comment by stevegrubb** [comment]
I'm going to close this. If this were reproducible with a recent kernel, please let us know.
