### ISSUE TITLE
Question: How to log in general all actions for the process generated by the execution of the file?

### ISSUE THREAD

**Issue by freedom1b2830** [linux-audit/audit-userspace#294]
I'm starting to write rules for a >>large<< project(``Consists of many programs, there is no way to track interactions without logging``).
I need to collect a list of all ``files|socket|shm`` and log with the key ``-k``.

**Comment by stevegrubb** [comment]
One way to do it is using the autrace program.

**Comment by freedom1b2830** [comment]
@stevegrubb how to exec app  from a specific user with autrace ?

**Comment by stevegrubb** [comment]
autrace requires CAP_AUDIT_CONTROL and maybe CAP_AUDIT_WRITE.

**Comment by freedom1b2830** [comment]
i thank you for your help

``CAP_AUDIT_CONTROL`` is needed to run autrace
but without ``CAP_AUDIT_WRITE`` it exit and gives an empty result )

need both
``CAP_AUDIT_CONTROL`` ``CAP_AUDIT_WRITE``

```sh
setcap "CAP_AUDIT_WRITE,CAP_AUDIT_CONTROL+ep"  /usr/bin/autrace
```
