### ISSUE TITLE
Process signal mask should be cleared before exec'ing plugins

### ISSUE THREAD

**Issue by sp1ff** [linux-audit/audit-userspace#295]
Was surprised to learn my plugin was blocking `SIGHUP`. Spent some time digging and found that my plugin's process sigmask consisted of precisely those signals on which `auditd` set `libev` signal watchers. From the `libev` docs:

"Both the signal mask (sigprocmask) and the signal disposition (sigaction) are unspecified after starting a signal watcher (and after stopping it again), that is, libev might or might not block the
signal, and might or might not set or restore the installed signal handler (but see EVFLAG_NOSIGMASK).

While this does not matter for the signal disposition (libev never sets signals to SIG_IGN, so handlers will be reset to SIG_DFL on execve), this matters for the signal mask: many programs do not expect certain signals to be blocked.

This means that before calling exec (from the child) you should reset the signal mask to whatever "default" you expect (all clear is a good choice usually)." -- [The Special Problem of Inheritance Over fork/exec/pthread_create](https://github.com/BeeswaxIO/libev/blob/master/ev.pod#the-special-problem-of-inheritance-over-forkexecvepthread_create)

I realize now why the plugins for which I could find source code start-off by un-blocking the signals in which they're interested, and that's what I'm doing in my own, but it would have saved me a lot of time had `auditd` followed this advice.

**Comment by stevegrubb** [comment]
It is a reality that a program has no idea of what the parent process has done and that it needs to set things the way it expects if it has the capabilities to do so. Auditd has no idea what systemd has done to it and has to set up the environment the way it expects or complain if it can't. This reality is why setuid applications clear their environment and specifically set a minimal PATH and locale.

**Comment by stevegrubb** [comment]
I have updated the auditd-plugins(5) man page with relevant documentation for plugin developers. Thanks for bringing this to my attention, it helped me understand that developers need to know a few things that were not documented. audit-3.1.1 has the new updated pages. Closing.
