### ISSUE TITLE
RFE: Add ability to rotate audit logs based on time

### ISSUE THREAD

**Issue by Cropi** [linux-audit/audit-userspace#297]
I am using ```max_log_file_action = ROTATE``` option to rotate the logs when the system has detected that the max file size limit has been reached. This works fine, but I would prefer to rotate logs based on time, e.g. daily, weekly, etc.
I know that it's possible to do this by sending a ```SIGUSR1``` signal to the audit daemon via a cron job on daily basis.

Are there any plans to introduce something like a time based logrotate feature? Thanks.

**Comment by stevegrubb** [comment]
There are no plans to add rotation based on time. It is easily setup via cron or systemd timers. So, we do not need to duplicate that functionality with the complications of DST or leap seconds.
