### ISSUE TITLE
auditctl --reset-lost outputs 2 when lost value is 0

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-userspace#31]
The command:
```
auditctl --reset-lost
```
prints a lost value of 2 when the lost value is 0.

This first run is from a fresh boot with a lost value of 10, giving the expected result:
```
[root@rawhide ~]# auditctl -s
enabled 1
failure 1
pid 337
rate_limit 0
backlog_limit 64
lost 10
backlog 0
backlog_wait_time 60000
loginuid_immutable 0 unlocked
[root@rawhide ~]# auditctl --reset-lost
lost: 10
[root@rawhide ~]# echo $?
0
```

Userspace and Kernel Versions:
```
[root@rawhide ~]# rpm -q audit
audit-2.8.1-1.fc28.x86_64
[root@rawhide ~]# uname -r
4.14.0-0.rc6.git0.1.1.secnext.fc28.x86_64
```

Here's a second run just after it has been reset:
```
[root@rawhide ~]# auditctl -s
enabled 1
failure 1
pid 337
rate_limit 0
backlog_limit 64
lost 0
backlog 0
backlog_wait_time 60000
loginuid_immutable 0 unlocked
[root@rawhide ~]# auditctl --reset-lost
lost: 2
[root@rawhide ~]# echo $?
0
```

The value is expected to be:
```
lost: 0
```

Here are the raw CONFIG_CHANGE records:
```
type=CONFIG_CHANGE msg=audit(1509727848.777:233): lost=0 old=10 auid=0 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 res=1
type=CONFIG_CHANGE msg=audit(1509727912.295:234): lost=0 old=0 auid=0 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 res=1
```

Interpreted:
```
type=CONFIG_CHANGE msg=audit(11/03/2017 12:50:48.777:233) : lost=0 old=10 auid=root ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 res=yes 
----
type=CONFIG_CHANGE msg=audit(11/03/2017 12:51:52.295:234) : lost=0 old=0 auid=root ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 res=yes
```

strace of the first run (lost 10), look for "error=":
```
recvfrom(3, {{len=76, type=NLMSG_ERROR, flags=0, seq=2, pid=2488758578}, {error=10, msg={{len=56, type=AUDIT_SET, flags=NLM_F_REQUEST|NLM_F_ACK, seq=2, pid=0}, "\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"...}}}, 8988, MSG_PEEK|MSG_DONTWAIT, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, [12]) = 76
recvfrom(3, {{len=76, type=NLMSG_ERROR, flags=0, seq=2, pid=2488758578}, {error=10, msg={{len=56, type=AUDIT_SET, flags=NLM_F_REQUEST|NLM_F_ACK, seq=2, pid=0}, "\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"...}}}, 8988, MSG_DONTWAIT, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, [12]) = 76
```

strace of the second run (lost 0), look for "error=":
```
recvfrom(3, {{len=36, type=NLMSG_ERROR, flags=0, seq=2, pid=3432050465}, {error=0, msg={len=56, type=0x3e9 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK, seq=2, pid=0}}}, 8988, MSG_PEEK|MSG_DONTWAIT, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, [12]) = 36
recvfrom(3, {{len=36, type=NLMSG_ERROR, flags=0, seq=2, pid=3432050465}, {error=0, msg={len=56, type=0x3e9 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK, seq=2, pid=0}}}, 8988, MSG_DONTWAIT, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, [12]) = 36
```

**Comment by stevegrubb** [comment]
Fixed in commit 56a708761347ba49ccdc2378d31133f01129f4f2

**Comment by rgbriggs** [comment]
On 2017-11-08 18:44, Steve Grubb wrote:
> Fixed in commit 56a708761347ba49ccdc2378d31133f01129f4f2

I don't understand this patch.

I see no other place where "lost: " appears in the code, so I'm guessing
this ouput format has been dropped and instead we get a full status?  If
that's the case, it'll break the existing test cases.

**Comment by stevegrubb** [comment]
The user space libraries are very old. They were not designed to have values passed back as an error. How do you distinguish an error from an actual legit value? If error is 0, then that means the command was OK and we want to look at the sequence number to ensure the result is for the command. So, how do you tell a sequence number from a legit error return if you are auditctl?

This all points to a case where something was designed in the kernel with the best of intentions but there are layers and layers of user space code that never considered the kernel might hand back a lone value rather than simply reporting success / fail. Everything else reports success/fail. The best thing to do is have auditctl ask for full status so there is no ambiguity about is this an error code, is this success, is the a sequence number?

**Comment by rgbriggs** [comment]
On 2017-11-08 20:38, Steve Grubb wrote:
> The user space libraries are very old. They were not designed to have
> values passed back as an error. How do you distinguish an error from
> an actual legit value? If error is 0, then that means the command was
> OK and we want to look at the sequence number to ensure the result is
> for the command. So, how do you tell a sequence number from a legit
> error return if you are auditctl?

The error is always -ve, whether it comes from the userspace, a syscall
or from kernel audit embedded in a netlink message.  The lost value is
always +ve.  Everything else in the kernel returns zero.

It appears the sequence value returned is never used other than to
indicate success and it is only used if the kernel returns zero.  So why
not just return that value returned from the kernel without mangling it?
Zero or positive means success.

> This all points to a case where something was designed in the kernel
> with the best of intentions but there are layers and layers of user
> space code that never considered the kernel might hand back a lone
> value rather than simply reporting success / fail. Everything else
> reports success/fail. The best thing to do is have auditctl ask for
> full status so there is no ambiguity about is this an error code, is
> this success, is the a sequence number?

And now the result is no longer synchronous and gives the new value that
may have been incremented since it was just reset because the status was
requested on a seperate call.  That could be fixed in the kernel by
sending an AUDIT_GET reply to this AUDIT_SET command, which is what I
was originally told to avoid.

Digging further...

audit_log_user_message()'s only user (setopt) doesn't use the sequence
number.

audit_log_acct_message(), audit_log_user_comm_message(),
audit_log_user_avc_message(), audit_log_semanage_message(),
audit_log_user_command()  appear to be unused within audit, but I'm
guessing we have no idea if there are external users of libaudit.

delete_all_rules() depends on seq returned from
audit_request_rules_list_data()

count_rules() also uses it.

So, reset_lost is broken worse than it was before this fix.

**Comment by rgbriggs** [comment]
Posted alternate fix upstream:
https://www.redhat.com/archives/linux-audit/2017-November/msg00025.html

**Comment by stevegrubb** [comment]
Updated patch has been applied.
