### ISSUE TITLE
Using access() in auparse lib

### ISSUE THREAD

**Issue by dimv36** [linux-audit/audit-userspace#312]
So, question is: Why is needed to use `access()` when form log list for auparse?

e. g. why is needed use `access()` in `setup_log_file_array()`? I have an application with SUID bit, but `auparse_init()` is failed due to no perms on `/var/log/audit` (real user can not read it, but EUID can read it!)

**Comment by stevegrubb** [comment]
Because in auparse_init, we do not open the file. We check if we can and let the caller know if there are problems. Reading the man page...it is very different than it was back in 2007. Today, it looks like we might want to call faccessat passing AT_EACCESS so that EUID is taken into account.

**Comment by dimv36** [comment]
So, all `access()` calls should change to `faccessat()`?

**Comment by stevegrubb** [comment]
I think so. I'll fix this up this week. I need to add some checks to configure.ac so that it can fallback to access on older systems.

**Comment by dimv36** [comment]
Thanks!

**Comment by stevegrubb** [comment]
Commit f14620d should fix this. Opted for faccessat. New glibc should do the right thing, old glibc only missed considering ACL's.

**Comment by dimv36** [comment]
I check on debian bookworm with patch applied. It's ok.

**Comment by stevegrubb** [comment]
Thanks for reporting the issue.
