### ISSUE TITLE
auditd fails to start in arm64be environment

### ISSUE THREAD

**Issue by juyin** [linux-audit/audit-userspace#318]
When I started auditd on arm64be, I found that it could not start normally.

![image](https://github.com/linux-audit/audit-userspace/assets/24436177/3921f203-ae64-4313-af22-45b332c299c3)

**Comment by stevegrubb** [comment]
Not all architectures are supported. There is a moratorium on adding new architectures until there is more community support.

https://listman.redhat.com/archives/linux-audit/2023-August/020036.html

**Comment by juyin** [comment]
> Not all architectures are supported. There is a moratorium on adding new architectures until there is more community support.
> 
> https://listman.redhat.com/archives/linux-audit/2023-August/020036.html

Thanks for your reply.
