### ISSUE TITLE
ausearch --checkpoint should create empty checkpoint file with date/time stamp when no events found

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-userspace#32]
ausearch's checkpoint feature should create an empty checkpoint file with the current date/time stamp when no events are found so that future invocations can start from that time.

```
ausearch --checkpoint <filename>
```
doesn't create a checkpoint file, even empty, when no events are found.  This is surprising, since future invocations of ausearch with the checkpoint option should simply start at that previous checkpointed point in time.  The file timestamp would be useful for subsequent --checkpoint operations.

**Comment by rgbriggs** [comment]
Raised on list to Burn's attention:
https://www.redhat.com/archives/linux-audit/2018-March/msg00134.html

**Comment by stevegrubb** [comment]
Patch has been merged. Closing.
