### ISSUE TITLE
aureport slow

### ISSUE THREAD

**Issue by mdidomenico4** [linux-audit/audit-userspace#322]
i'm trying to read in an audit file, which admittedly is very large >170GB.  however, i try to read it in using ```aureport -if``` its taking a long time.  i left it for an hour before i gave up.

so i tried feeding it in via ```dd``` so i could get a progress report of how much its read in as it goes.  it seems to be very slow reading in the data

```
[root@logs]# dd if=pluto-auditd bs=1M status=progress | aureport --summary
Summary Report
======================
193986560 bytes (194 MB, 185 MiB) copied, 460 s, 422 kB/s
```

the filesystem the file resides on is not slow by any stretch

```
[root@logs]# dd if=pluto-auditd of=/dev/null bs=1M status=progress
11779702784 bytes (12 GB, 11 GiB) copied, 13 s, 906 MB/s^C
11744+0 records in
11743+0 records out
12313427968 bytes (12 GB, 11 GiB) copied, 13.7124 s, 898 MB/s
```

any thoughts on what aureport is doing or how i might troubleshoot the issue?  a simple strace of the process didn't reveal anything remarkable

**Comment by stevegrubb** [comment]
aureport and ausearch have to assume that the events are interlaced. The kernel makes no effort to serialize the events and leaves that as an exercise for user space. That means events go onto a list of lists until it's determined they are complete. Once that is determined, they get processed. I have profiled aureport and have made a comment at the function that is the hotspot (don't remember the name offhand), but there is no easy path to make it faster. They both use a lot of linked lists which is not the fastest, but they are correct.

**Comment by mdidomenico4** [comment]
ok, makes sense.  if i understand what you're saying is that since an audit "record" is really a culmination of several lines of the log file, the tool needs to combine all those before it processes the record.  thanks for the info

**Comment by stevegrubb** [comment]
Yes, it has to deinterlace events and then determine they are complete before processing. If it weren't for this, it would be faster. I have profiled it and it's about as fast as it can go using linked lists. It even mmaps the files to gain 5%. If you have the luxury of compiling it yourself, CFLAGS+= -O3 -mtune=native -march=native might help (won't be portable, though).

**Comment by mdidomenico4** [comment]
thanks.  i might give it a whirl, but doubt it'll help much.  we were hoping to use the aureport --summary as a sanity check before the data gets uploaded into a SEIM, just to make sure we're actually capturing stuff.  but with our large amount of audit data it seems that's not going to work out.
