### ISSUE TITLE
Aureport on stream of data

### ISSUE THREAD

**Issue by chazoz** [linux-audit/audit-userspace#324]
I would like to know how can I rum aureport on a stream of data, i.e auditd logs streamed to elk

**Comment by chazoz** [comment]
Hello

So elk is just one use case, but any kafka / siem / databases that stores
audit log are relevant here.
How can I convert text output to be formated so that aureport can be piped
and give insights ?

Thank you

בתאריך יום ד׳, 20 בספט׳ 2023, 19:02, מאת Steve Grubb ‏<
***@***.***>:

**Comment by stevegrubb** [comment]
I have no idea what the output is as I have no access to any of those. Once you take the logs into something else, typically you use the tools provided by that something else. If their tools can't extract the data back into its original format, you can't use tools from the original source (auditd).

**Comment by chazoz** [comment]
So just to clarify, having raw, textual auditd logs can be piped to
aureport ?

בתאריך יום ה׳, 21 בספט׳ 2023, 17:45, מאת Steve Grubb ‏<
***@***.***>:

**Comment by stevegrubb** [comment]
Yes. For example, try the following:
 ausearch --start today --key module-load --raw | aureport -x --summary -i

**Comment by stevegrubb** [comment]
Looks like this ticket can be closed. If you have any further questions just ask.

**Comment by chazoz** [comment]
Yes please, 2 questions :

1) Is there a way to run aureport on updating auditd logs ? That is, not
running aureport on all logs, just updating the last aureport with the
recent addition of logs ?
2) Could aureport run on combined auditd logs from more than one computor
and produce multiple outputs ?

Thank you

בתאריך יום ד׳, 11 באוק׳ 2023, 23:22, מאת Steve Grubb ‏<
***@***.***>:
