### ISSUE TITLE
how can i use this project for audit with linux kernel 2.6 like centos6?

### ISSUE THREAD

**Issue by actanble** [linux-audit/audit-userspace#326]
**NOTE:** Please refer to the [Reporting Bug and Requesting Features](https://github.com/linux-audit/audit-documentation/wiki/Reporting-Bugs-and-Requesting-Features) wiki page before creating any new GitHub issues.

how can i use this project for linux kernel 2.6 like centos6? 

in another say, how can i change to use some function of this project for centos6.

**Comment by stevegrubb** [comment]
Centos6 already has an audit package that matches it's kernel. Just use that one. The one in this repo is for kernels that are later. If you need newer features, your best move is to upgrade from Centos6 to a newer OS.

**Comment by stevegrubb** [comment]
I think this ticket can be closed. If you have any other questions, feel free to ask.
