### ISSUE TITLE
audisp-remote does never close connection

### ISSUE THREAD

**Issue by timp87** [linux-audit/audit-userspace#33]
Turns out audisp-remote plugin does never close connection even on stop/restart/etc.
If central receiving auditd has the following configuration
```
tcp_client_max_idle = 0
tcp_max_per_addr = 1
```
and sending host is restarted you'll loose audit messages for a long time (perhaps for tcp timeout?).
On the receiving side you'll get
```
type=DAEMON_ACCEPT msg=audit(1512058612.591:6605): op=dup addr=${client-ip} port=36242 res=no
```
and it will refuse any connection from client until previous one considered inactive.

I know a WA - set tcp_client_max_idle to relatively small value or increase tcp_max_per_addr.
But in general I think described behavior is not great.

**Comment by timp87** [comment]
The behavior is the same no matter if it's latest 2.8.1 or 2.7.6 from CentOS 7.4

**Comment by stevegrubb** [comment]
I looked at the code in audisp-remote. It seems to be doing the right thing. So, I'm going to guess that auditd is not detecting the closed connection as it should. By setting tcp_client_max_idle = 0 it is literally telling auditd to not timeout a dead socket. I'll take a look and see if auditd can do a better job of detecting closed connections by other means.

**Comment by timp87** [comment]
Well, I'm not sure I fully understand how you intended this functionality, at least why you want now to look at the auditd side.
I didn't look at the audisp-remote code, but I looked at the network traffic it produces via tcpdump.
audisp-remote never sends neither FIN nor RST to close the connection. Never, no matter what signal it got.
To reduce misunderstanding could you please desribe what the right thing means it this context?

**Comment by stevegrubb** [comment]
I think audisp-remote code is good because of the way it tears down the connection.

https://github.com/linux-audit/audit-userspace/blob/master/audisp/plugins/remote/audisp-remote.c#L610

	if (sock >= 0) {
		shutdown(sock, SHUT_RDWR);
		close(sock);
}

That should be a proper disconnect. 

But on the auditd side, it may not see any data that is readable. The daemon side uses libev which is an asynchronous event handling library. Since that abstracts all the events that the audit daemon handles, it may not be able to handle the shutdown or maybe I need to do something to tell it I want notification of closures. It'll take some investigating.

**Comment by timp87** [comment]
Ok, I think I managed to localize the problem.
Nothing wrong with auditd or audisp* code. Everything works as expected. Audisp-remote sends FIN auditd replies with FIN+ACK, etc.
To prove this I tried to stop auditd with 
```
service auditd stop
```
which ignore some systemd options. I saw FIN.
Also I tried to comment *RefuseManualStop=yes* option in systemd unit file for auditd. Then stopped it via systemctl. Works great, audisp-remote closes connection.

So returning to the problem I described before: I didn't see FIN or any packet closing connection in case if I rebooted client host via *reboot* command. I suppose this means the issue is in systemd unit configuration, perhaps systemd turns network off before auditd. I'll post here when I get more information just for the history.
I think we can close this PR, nothing to fix in your code.

**Comment by timp87** [comment]
The answer is written in /usr/lib/systemd/system/auditd.service
It suggests to add _network-online.target_ to _After=_ directive. This makes reboot work properly with connection close. But it breaks auditd startup after reboot =)
```
Dec  4 18:49:19 auclient2 systemd: Found ordering cycle on sysinit.target/start
Dec  4 18:49:19 auclient2 systemd: Found dependency on auditd.service/start
Dec  4 18:49:19 auclient2 systemd: Found dependency on network-online.target/start
Dec  4 18:49:19 auclient2 systemd: Found dependency on network.service/start
Dec  4 18:49:19 auclient2 systemd: Found dependency on basic.target/start
Dec  4 18:49:19 auclient2 systemd: Found dependency on sockets.target/start
Dec  4 18:49:19 auclient2 systemd: Found dependency on dbus.socket/start
Dec  4 18:49:19 auclient2 systemd: Found dependency on sysinit.target/start
Dec  4 18:49:19 auclient2 systemd: Breaking ordering cycle by deleting job auditd.service/start
Dec  4 18:49:19 auclient2 systemd: Job auditd.service/start deleted to break ordering cycle starting with sysinit.target/start
```
Ugly WA is to remove _sysinit.target_ from _Before=_ directive.

I found that also breaks _systemd-update-utmp.service_. WA is to remove  _auditd.service_ from _After=_ directive in systemd-update-utmp.service unit.
I think I have to report this to RedHat or Fedora (?) bug tracker.

Please, close this particular PR.
