### ISSUE TITLE
ARM-NONE-LINUX-GNUEABI not able to cross compile in ARM 

### ISSUE THREAD

**Issue by ProNooB7** [linux-audit/audit-userspace#344]
When I am trying to compile uisng **arm-none-linux-gnueabi** , It is resulting in below Error 
/../lib/gcc/arm-none-linux-gnueabi/4.6.1/../../../../arm-none-linux-gnueabi/bin/ld: warning: libaudit.so.1, needed by ../../../auparse/.libs/libauparse.so, not found (try using -rpath or -rpath-link)
../../../auparse/.libs/libauparse.so: undefined reference to `audit_detect_machine'
../../../auparse/.libs/libauparse.so: undefined reference to `audit_msg_type_to_name'
../../../auparse/.libs/libauparse.so: undefined reference to `audit_flag_to_name'
../../../auparse/.libs/libauparse.so: undefined reference to `audit_elf_to_machine'
../../../auparse/.libs/libauparse.so: undefined reference to `audit_name_to_msg_type'
../../../auparse/.libs/libauparse.so: undefined reference to `audit_syscall_to_name'
../../../auparse/.libs/libauparse.so: undefined reference to `audit_ftype_to_name'
../../../auparse/.libs/libauparse.so: undefined reference to `secure_getenv'
../../../auparse/.libs/libauparse.so: undefined reference to `audit_machine_to_name'
../../../auparse/.libs/libauparse.so: undefined reference to `audit_errno_to_name'
collect2: ld returned 1 exit status
make[4]: *** [audisp-syslog] Error 1
Makefile:486: recipe for target 'audisp-syslog' failed

I tried to build it with **arm-linux-gnueabi** , it compiled successfully , but it is not arm compatible , hence when ran results in some gibberish characters 
file auditd (when compiled with arm-linux-gnueabi)
auditd: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, stripped

usr/local/sbin # ./auditd -s enable ¨¿?!Litd: line 1: «F/,C?TH³: not found./auditd: line 1: can't open ??U© ¿??BE???: no such file ??ûOz?q@û´=??m: not found??³¢? ./auditd: line 1: can't create P_@x!@8: Read-only file system ./auditd: line 1: ELF: not found ./auditd: line 1: Z?¨3~i?gx$zq?:: not??Z: no such file ./auditd: line 1: ¤p}W?¯?jZL½?¯KµR?ûn·^D?4: not found ./auditd: line 2: : not found ./auditd: line 3: syntax error: unexpected "("

this is the configure command that i am using 
configure --host=**arm-linux-gnueabi** --disable-zos-remote --prefix=/usr/local --enable-systemd --without-python3 --without-python -with-arm

Please chim in for help

**Comment by stevegrubb** [comment]
I don't test any cross-compilation. People have contributed patches to allow that to work, but it is fragile and has broke before. If it works, that's fine and all is good. If it breaks, it may go a couple releases before anyone spots a problem. And it may go a couple releases before a PR fixes the problem.

**Comment by stevegrubb** [comment]
You may need to define some environmental variable in the call to configure for example CC=path-to-cross-compiler

**Comment by 994179396** [comment]
You need to change into the src root directory and exec the autogen.sh before run configure cmd

**Comment by stevegrubb** [comment]
I don't think there a lot that I can add to this. I'll update the README file to mention the cross compilation situation.
