### ISSUE TITLE
Add more ways to encrypt connection auditd client-server besides krb5

### ISSUE THREAD

**Issue by timp87** [linux-audit/audit-userspace#35]
This is a proposal, not a bug report.

There is only one way to pass audit messages to remote side in a secure way. It's Kerberos 5.
But it would be handy if auditd and audisp-remote had more secure ways. For example, via TLS/SSL.

**Comment by stevegrubb** [comment]
I keep the future road map in the TODO file. Adding TLS support is already on the roadmap.

https://github.com/linux-audit/audit-userspace/blob/master/TODO#L5

I have a half written patch to use GNUTLS that I'll be merging later next year. Opening this issue is not necessary.
