### ISSUE TITLE
autrace 

### ISSUE THREAD

**Issue by Cherkah** [linux-audit/audit-userspace#360]
i've recently installed audit 4.0.1 on my Endeavouros. On Archlinux audit wiki Autrace is mentioned as an strace like but nowhere .../bin/autrace is installed on my device.

Does audit pkg for archlinux include autrace or did it have been removed from audit pkd ?

Thanks

**Comment by stevegrubb** [comment]
The audit package was restructured per the following email:

https://lists.linux-audit.osci.io/archives/list/linux-audit@lists.linux-audit.osci.io/thread/EX2RT5YMJCCMGZDSRJT6SXYKIE3T77IO/

There were no objections. The old code for that utility should still compile. The API it uses should not have changed.

**Comment by Cherkah** [comment]
ok so autrace have been dropped. helas
thanks
