### ISSUE TITLE
A couple of suspicious places in source code.

### ISSUE THREAD

**Issue by Yugend** [linux-audit/audit-userspace#362]
I was checking audit-userspace package using static code analyzer and find a few strange places, which could be dangerous. Most of them I tried to fix in [#361](https://github.com/linux-audit/audit-userspace/pull/361)

And I found two more that I was afraid to fix on my own, because I'm not so sure about them.

1. src/auditctl.c file, [395 line.](https://github.com/linux-audit/audit-userspace/blob/aa40e63c3a13b0136213f816ed0e2e9f8a6ca6ca/src/auditctl.c#L395) The memcmp function does not compare buffers completely. Probably this memcmp() call should be look like `memcmp(tmprule.mask, rule_new->mask, AUDIT_BITMASK_SIZE * sizeof(__u32))`
2. auparse/nvlist.c file, [68 line.](https://github.com/linux-audit/audit-userspace/blob/aa40e63c3a13b0136213f816ed0e2e9f8a6ca6ca/auparse/nvlist.c#L68) Size of allocated memory for `l->array` is not big, but for security it should be checked for NULL.

Maybe this code is safe for some reason, but I didn't notice it. In that case, I'm sorry to disturb you.

**Comment by stevegrubb** [comment]
1. Yes, I think you're right.
2. realloc is a tricky function to get right. In this case, it is reallocating a buffer that was already created. If realloc fails, the original buffer still exists but whatever you are doing that needs more space can't be done. I suppose the returned value should be caught in a tmp variable so it can be checked without overwriting the pointer to the original buffer. If it is ok, then assign it to l->array.
