### ISSUE TITLE
local_events

### ISSUE THREAD

**Issue by LidiYuan** [linux-audit/audit-userspace#363]
You can see the following code in the source code  (auditd.c) 
`#ifndef DEBUG
	/* Make sure we can do our job. Containers may not give you
	 * capabilities, so we revert to a uid check for that case. */
	if (!audit_can_control()) {
		if (!config.local_events && geteuid() == 0)
			;
		else {
			fprintf(stderr,
		"You must be root or have capabilities to run this program.\n");
			return 4;
		}
	}
#endif`

Is there a problem with the configuration file for config.local_events in this code, as they have not yet read data from the configuration file。

**Comment by stevegrubb** [comment]
Yes, it appears you are correct. I moved the check down a few lines to after load_config().
