### ISSUE TITLE
Does audit register symlink events?

### ISSUE THREAD

**Issue by dimv36** [linux-audit/audit-userspace#373]
Does audit can register symlink events?

**Comment by rgbriggs** [comment]
On 2024-05-13 07:05, Dmitry Voronin wrote:
> Does audit can register symlink events?

Nope.  https://github.com/linux-audit/audit-kernel/issues/94

**Comment by stevegrubb** [comment]
I guess the reporter should add themselves to kernel issue 94. Closing this one.
