### ISSUE TITLE
In-house implementation of `strndupa` is faulty

### ISSUE THREAD

**Issue by MIvanchev** [linux-audit/audit-userspace#381]
```
#ifndef HAVE_STRNDUPA
static inline char *strndupa(const char *old, size_t n)
{
	size_t len = strnlen(old, n);
	char *tmp = alloca(len + 1);
	tmp[len] = 0;
	return memcpy(tmp, old, len);
}
#endif
```

This code is undefined behavior, a pointer to stack memory is returned but the stack memory is reclaimed immediately. See our build for Void Linux https://github.com/void-linux/void-packages/pull/50666

**Comment by Cropi** [comment]
Hi @MIvanchev, can you try it out with my recent patch? https://github.com/linux-audit/audit-userspace/pull/385

**Comment by MIvanchev** [comment]
Yes, I'll take a look ASAP.
