### ISSUE TITLE
Build error:  multiple definition of `aulookup_destroy_uid_list'

### ISSUE THREAD

**Issue by JonLiu1993** [linux-audit/audit-userspace#391]
Hey, when I [update](https://github.com/microsoft/vcpkg/pull/40703) audit to the latest version 4.0.2 I get a build error in linux:
````
/usr/bin/ld: /usr/bin/ld: ../auparse/.libs/libauparse.a(interpret.o): in function `aulookup_destroy_uid_list':
/mnt/vcpkg-ci/b/audit/x64-linux-dbg/auparse/.././../src/v4.0.2-90950820cd.clean/auparse/interpret.c:598: multiple definition of `aulookup_destroy_uid_list'; ausearch-lookup.o:/mnt/vcpkg-ci/b/audit/x64-linux-dbg/src/.././../src/v4.0.2-90950820cd.clean/src/ausearch-lookup.c:246: first defined here
../auparse/.libs/libauparse.a(interpret.o): in function `aulookup_destroy_uid_list':
````

I changed function `aulookup_destroy_uid_list(void)` to `aulookup_destroy_uid_nvl_list(void)` in ausearch-lookup.h and ausearch-lookup.c file fix the error. To avoid multiple definitions of the same function name：
https://github.com/linux-audit/audit-userspace/blob/4e6deae41d4646d28bb3ba9524a8a227a38ccd0b/auparse/interpret.c#L597
https://github.com/linux-audit/audit-userspace/blob/4e6deae41d4646d28bb3ba9524a8a227a38ccd0b/src/ausearch-lookup.c#L245 

I want to know if this repair is feasible? Or do you have any repair suggestions? Thanks!

**Comment by stevegrubb** [comment]
It's really odd that gcc doesn't report this on my system even though the compile flags are for LTO. But yes, renaming the function is the fix. I doubt it has any real world implications as the lists are destroyed at exit. If the wrong one is cleared, exit finishes returning the memory. Thanks for pointing this out.

**Comment by stevegrubb** [comment]
ok, looked more into this. The function in auparse is declared within a file where the prototype is guarded by

_Pragma("GCC visibility push(hidden)")

And this is confirmed by 

readelf -sW /usr/lib64/libauparse.so.0.0.0 | grep aulookup_destroy_uid_list 

finding nothing. I guess the compiler you are using does not recognize the pragma directive making it hidden.

**Comment by JonLiu1993** [comment]
@stevegrubb, Thanks for your investigation and reply. Since we have many ports to test, we cannot easily modify the compiler in the pipeline of our test PR. Do you agree that I can use such a patch to temporarily solve this problem?

**Comment by stevegrubb** [comment]
Yes, if that works for now, go with it. But the audit system uses visibility to prevent internal API's from being used by third party developers. Maybe I'll rename the function to prevent collisions.

**Comment by JonLiu1993** [comment]
> Yes, if that works for now, go with it. But the audit system uses visibility to prevent internal API's from being used by third party developers. Maybe I'll rename the function to prevent collisions.

Thanks, I'll remove this patch in the next release once you fix this upstream.

**Comment by stevegrubb** [comment]
commit a89664b should fix this.
