### ISSUE TITLE
BUG: auditctl man page is missing "-F exe" 

### ISSUE THREAD

**Issue by The-Mule** [linux-audit/audit-userspace#4]
Audit supports filtering events by executable name - auditctl option '-F'  can be given field "exe". However, this new functionality is not documented in man page yet.

**Comment by pcmoore** [comment]
I'm only commenting here to get the attention of @stevegrubb .  Steve, what is your policy on using the issue tracker and/or pull request feature of the audit-userspace repo?

**Comment by The-Mule** [comment]
Steve already told me that this issue is already resolved in 2.6.7 and
hence I am ready to close this issue. But I am also interested if you
prefer RHBZ or githut issues. I am perfectly fine with both ways. However
it might be better to to use the old way (RHBZ) since bugzilla numbers are
referenced in the changelogs and so on. Moreover, most bugs and comments
should be public(, hopefully). I was just tempted to try this :).

**Comment by pcmoore** [comment]
For the [linux-audit/audit-kernel](https://github.com/linux-audit/audit-kernel), [linux-audit/audit-testsuite](https://github.com/linux-audit/audit-testsuite), and [linux-audit/audit-documentation](https://github.com/linux-audit/audit-documentation) we use the following policy:

* Upstream bugs/issues are tracked via the associated GitHub issue tracker
* Fedora/RHEL bugs/issues are tracked via the Red Hat Bugzilla

In some cases this may mean that we have both a GitHub and RHBZ issue, in which case the upstream GitHub issue should contain all of the important information, with the RHBZ issue simply referencing the upstream GitHub issue.  This policy is intended to make audit development more transparent, and distribution neutral.

@stevegrubb tends to do his own thing and not necessarily follow what the rest of us are doing; he has mentioned shifting over to GitHub\[1\] (at least for the code repository) at some point in the future but I don't believe he has mentioned any firm plans about what he wants to do with issue tracking once he makes the transition.  If he doesn't comment here, we can discuss it at our next team meeting.

\[1\] The [linux-audit/audit-userspace](https://github.com/linux-audit/audit-userspace) repository here on GitHub is simply a mirror of Steve's SVN repository that I sync on a weekly basis; Steve does not currently maintain this repository, although we have discussed transitioning from SVN to GitHub, there is just not a firm date at this point.

**Comment by stevegrubb** [comment]
This was fixed in commit 1386 over a month ago. Thanks for reporting this.
