### ISSUE TITLE
RFE: support audit container ID filtering

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-userspace#40]
Add userspace audit tool support for the features introduced by kernel audit container ID support.

- filtering on container ID
- ausearch support

See: https://github.com/linux-audit/audit-kernel/issues/91
See: https://github.com/linux-audit/audit-kernel/wiki/RFE-Audit-Container-ID

**Comment by rgbriggs** [comment]
Posted RFC v1 userspace patch for auditctl containerid filter support:
https://www.redhat.com/archives/linux-audit/2018-March/msg00030.html
https://lkml.org/lkml/2018/3/5/82

**Comment by rgbriggs** [comment]
Posted v2 userspace patchset upstream:
https://www.redhat.com/archives/linux-audit/2018-March/msg00124.html
https://lkml.org/lkml/2018/3/16/210

**Comment by rgbriggs** [comment]
Posted v3 patchset upstream:
https://www.redhat.com/archives/linux-audit/2018-June/msg00059.html
https://lkml.org/lkml/2018/6/6/626

**Comment by rgbriggs** [comment]
Posted v5:
https://www.redhat.com/archives/linux-audit/2019-March/msg00036.html
https://lkml.org/lkml/2019/3/15/544

**Comment by rgbriggs** [comment]
post v6:
https://www.redhat.com/archives/linux-audit/2019-April/msg00062.html
https://lkml.org/lkml/2019/4/9/774

**Comment by rgbriggs** [comment]
Test case v1 PR: https://github.com/linux-audit/audit-testsuite/pull/83

**Comment by rgbriggs** [comment]
2019-09-18:
post v7:
        https://www.redhat.com/archives/linux-audit/2019-September/msg00038.html
        https://lkml.org/lkml/2019/9/18/1138
        https://github.com/linux-audit/audit-userspace/compare/master...rgbriggs:ghau40-containerid-filter.v7.0
        http://people.redhat.com/~rbriggs/ghak90/git-247fe71

**Comment by rgbriggs** [comment]
post v8
        https://lkml.org/lkml/2019/12/31/244
        https://lore.kernel.org/lkml/1577822301-19760-1-git-send-email-rgb@redhat.com/T/#t
        https://www.redhat.com/archives/linux-audit/2019-December/msg00066.html
latest testsuite pr: https://githu.com/linux-audit/audit-testsuite/pull/91
A repo of the code is here:
  git@github.com:rgbriggs/audit-userspace.git ghau40-containerid-filter.v8
And test rpms built from it are here:
  people.redhat.com/~rbriggs/ghak90/git-47ad4ca

**Comment by rgbriggs** [comment]
Post v9 kernel:
https://www.redhat.com/archives/linux-audit/2020-June/msg00108.html
https://lkml.org/lkml/2020/6/27/205

Post v9 userspace:
https://www.redhat.com/archives/linux-audit/2020-June/msg00122.html

**Comment by khimaros** [comment]
did this make it into a particular kernel/audit-userspace release?

i'm very interested in this, especially if it allows filtering at the rule level.

**Comment by stevegrubb** [comment]
No. The work is still ongoing.

**Comment by stevegrubb** [comment]
Closing this out. A tracker for this is not needed. When a patch is available, just do a pull request.
