### ISSUE TITLE
As ino_t and dev_t can now be 64 bit quantities, need to update ausearch checkpoint code to support such sizes

### ISSUE THREAD

**Issue by burnalting** [linux-audit/audit-userspace#404]
Inode numbers (ino_t) and device identifiers (dev_t) are now 64 bit quantities. The ausearch checkpointing code, which records the inode number of the last audit log file processed along with the device identifier where the file resides,  treat them as 32 bit quantities.

**Comment by Cropi** [comment]
Fixed in https://github.com/linux-audit/audit-userspace/pull/405
