### ISSUE TITLE
Certain printfs of an event's seconds value need to be uplifted to current time_t size of int64_t

### ISSUE THREAD

**Issue by burnalting** [linux-audit/audit-userspace#406]
In a number of routines, the value of an event's second counter is printed with the format specifier of %ld rather than %lld.

**Comment by Cropi** [comment]
Can I assume that you refer to the following part of the code? https://github.com/linux-audit/audit-userspace/blob/master/src/ausearch-checkpt.c#L182
```
	if (sscanf(rest, TIME_T_SPECIFIER ".%03u:%lu 0x%X", &e->sec, &e->milli,
						&e->serial, &e->type) != 4) {
		fprintf(stderr, "Malformed output/event checkpoint line "
			"after node - [%s]\n", lbuf);
		checkpt_failure |= CP_STATUSBAD;
		return 1;
	}
```
What do you thin about https://github.com/linux-audit/audit-userspace/pull/408 ?

**Comment by burnalting** [comment]
#408 is certainly valid as we are reading directly into a time_t value.

This particular issue (and associated PR - https://github.com/linux-audit/audit-userspace/pull/407) deals with the emitting of the seconds valuee.
