### ISSUE TITLE
RFE: extend exclude filter support to subject credentials

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-userspace#5]
Please apply these patches:
  https://github.com/linux-audit/audit-userspace/pull/1
  https://www.redhat.com/archives/linux-audit/2016-August/msg00045.html
Kernel part:
    https://github.com/linux-audit/audit-kernel/issues/5
upstreamed 2016-06-27 86b2efb:
  https://www.redhat.com/archives/linux-audit/2016-June/msg00064.html
with an addition to add feature bitmap support posted 2016-08-18:
  https://www.redhat.com/archives/linux-audit/2016-August/msg00037.html
Test upstreamed:
  https://github.com/linux-audit/audit-testsuite/commit/447acf74c4f81787c9334b446c85690042f1ac59
Please re-open the following issue when this issue is resolved:
  https://github.com/linux-audit/audit-testsuite/pull/23#issuecomment-250208080

**Comment by rgbriggs** [comment]
@pcmoore I get " You can't perform that action at this time. " when I try to set a milestone of "audit-2.7".

**Comment by pcmoore** [comment]
@rgbriggs Problems with adding and applying milestones is separate from this issue, let's try to keep the comments here relevant to the original RFE request.  I'll follow up with you in email.

**Comment by stevegrubb** [comment]
This went in as commit 1403.
