### ISSUE TITLE
auditd message format

### ISSUE THREAD

**Issue by dimv36** [linux-audit/audit-userspace#54]
Hi, 

can I write arbitrary message via libaudit API like this:

attr="test test test"

or any value must be only string without spaces? Thanks.

**Comment by stevegrubb** [comment]
If the value side has any special characters in it, then it must be encoded. audit_value_needs_encoding() will tell you if it need encoding. To encode use audit_encode_value. If you want something that figures it all out, then use audit_encode_nv_string().

**Comment by dimv36** [comment]
Thanks a lot!
