### ISSUE TITLE
Audit events sending and user

### ISSUE THREAD

**Issue by dimv36** [linux-audit/audit-userspace#56]
Hi,

Can I send any events via API to audit log under user without rights (e. g. I'm not root)? I change log group in auditd.conf, but it does not work. Thanks!

**Comment by stevegrubb** [comment]
The kernel requires that you have CAP_AUDIT_WRITE. This is to make sure that only privileged processes can write to the audit logs. If any process could write to audit, we'd have a mess and trouble trying to tell real events from spoofed events by an attacker.
