### ISSUE TITLE
auditd and message format: unescaping

### ISSUE THREAD

**Issue by dimv36** [linux-audit/audit-userspace#58]
Hi, I asked for escaping non-standart ASCII raws in #56 previously.

Now I wrote messages into auditd daemon and want to decode them out.
Auditd' Python API wrote me unescaped values like this:

event=D09FD0BED0B4D0BAD0BBD18ED187D0B5D0BDD0B8D0B5

how can I decode them?

**Comment by rgbriggs** [comment]
On 2018-08-01 14:32, Dmitry Voronin wrote:
> Hi, I asked for escaping non-standart ASCII raws in #56 previously.
> 
> Now I wrote messages into auditd daemon and want to decode them out.
> Auditd' Python API wrote me unescaped values like this:
> 
> event=D09FD0BED0B4D0BAD0BBD18ED187D0B5D0BDD0B8D0B5
> 
> how can I decode them?

ausearch -i

**Comment by dimv36** [comment]
Unfortunately, it's not working for me. Does libaudit work fine for non-ascii symbols?

**Comment by dimv36** [comment]
Guys,

I try to encode my non-ASCII value (and ASCII value with spaces) via audit_encode_nv_string() and send to audit log successfully. I used an event type AUDIT_TRUSTED_APP.

But I can't get decoded value via ausearch -i or Python audit API. Please, help!
I'm using libaudit 2.8.3.

**Comment by dimv36** [comment]
I found, that attrs, which are needed to be unescaped, are determined in auparse_interp_adjust_type().

So, I make a simple patch for me for unescaping those attrs for my case depended on event_type AUDIT_TRUSTED_APP. But I don't think, that good idea. As for me, configurable list of attributes which must be unescaped is best solution for my problem.

So, my proposal:
* Add configuration value in aduitd.conf (?) for list of unescaped attributes in event;
* Load those values into list and check attribute name in auparse_interp_adjust_type() for unescaping
* If attribute in list, use au_unescape

**Comment by stevegrubb** [comment]
Yes, that sounds like a good idea. But I am not sure about where to put the field list. Ausearch needs the information and nothing else does. So, it might be a command line option like --escape-list. Then you can make a bash alias so that anytime you run ausearch it automatically uses the list. It would also need to apply only to AUDIT_TRUSTED_APP and AUDIT_KERNEL_OTHER records to ensure it cannot be abused for other records.

**Comment by dimv36** [comment]
I'm not think, that only ausearch is needed in those list.
Because someone (e.g. me) works with audit log via API. In this case, external file with attributes list will be more preferable rather than command line argument. When deparsing key-value pair those list will be loaded from external file and items will be unescaped.

As for your idea about command-line argument for auserch. If user selected them, than attributes to be unescaped from command like will be preferred than stored in attributes file.

**Comment by stevegrubb** [comment]
OK. I'll wait for the patch to review it. In general I like the concept.

**Comment by dimv36** [comment]
Steve,

I'll be on vacation for two weeks, so I will make a patch in September.

**Comment by stevegrubb** [comment]
That is fine.

**Comment by stevegrubb** [comment]
I'm going to close this issue. I'll follow up on the pull request.
