### ISSUE TITLE
RFE: add support for namespace ID record types

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-userspace#59]
Add support for namespace identifier record types.  There will need to be new auxiliary record types for namespace identifiers for existence, add, delete and set/change events.

Currently the set appears to be:
`AUDIT_NS_{INFO,{INIT,DEL,SET}_{MNT,UTS,IPC,USER,PID,NET,CGRP}}`

See: https://github.com/linux-audit/audit-kernel/issues/32

**Comment by stevegrubb** [comment]
Closing this out. A tracker for this is not needed. When a patch is available, just do a pull request.
