### ISSUE TITLE
TODO file is not shipped in the tarball anymore

### ISSUE THREAD

**Issue by bigon** [linux-audit/audit-userspace#62]
Hello,

For some reasons, the TODO file is not shipped in the 2.8.4 released tarball anymore

Maybe the file should be added explicitly to the EXTRA_DIST variable?

**Comment by stevegrubb** [comment]
Hi,

Yes, that is by design. The 2.8.x branch is a maintenance branch. It no longer has goals. It gets bugfixes cherry picked from the master branch. The TODO file is on the master branch and will be in audit-3.0 when that is released.

**Comment by bigon** [comment]
OK so I guess this can be closed
