### ISSUE TITLE
audit FTBFS on several debian architectures

### ISSUE THREAD

**Issue by bigon** [linux-audit/audit-userspace#65]
Hello,

The last version of audit (2.8.4) FTBFS on several debian architectures withe the following error:

> /usr/bin/ld: lookup_test.o: file not recognized: file truncated

I believe this is an issue because the tests are run in parallel and that doesn't cope well with `AUTOMAKE_OPTIONS = no-dependencies`? Must the test be run with -j1? Shouldn't the Makefile declare `.NOTPARALLEL` or `MAKEFLAGS += -j1`?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907538
https://buildd.debian.org/status/logs.php?pkg=audit&ver=1%3A2.8.4-1

**Comment by bigon** [comment]
https://github.com/linux-audit/audit-userspace/pull/63

**Comment by bigon** [comment]
No, it doesn't change anything it still fails sometimes, I think that @AdrianBunk (PR #63) is actually the good solution here I tried it and lookup_test is not built twice

**Comment by stevegrubb** [comment]
Has something changed in the build system since 2.8.3 was built? I'm curious why this is happening now and not in the past. I also still cannot reproduce this. But it seems like make job control is getting out of sync with itself.

**Comment by bigon** [comment]
I can reproduce this with a high parallelism number like `make -j8` (but not all the time)

Looking at the generated Makefile, the check_PROGRAMS are always built before the check: target from the Makefile.am is run, so at best, declaring dependencies on the program is useless

With the little test case:

```
./autogen.sh&& ./configure && make -j8 && make -j8 check
rm ./auparse/test/lookup_test
make -j1 check|grep lookup_test
```
As you can see lookup_test is built twice

**Comment by stevegrubb** [comment]
I accepted pull request #66 as the proper fix. Thanks for reporting this issue.
