### ISSUE TITLE
-F unknown field: exe

### ISSUE THREAD

**Issue by TyMac** [linux-audit/audit-userspace#72]
Attempting to use the PCI DSS rules on ubuntu 16.04, I get an error when loading the 10.2.5.b rules:

`auditctl -a always,exit -F arch=b64 -S setuid -F a0=0 -F exe=/bin/su -F key=10.2.5.b-elevated-privs-session
-F unknown field: exe`

Not sure why this rule does not work and large amounts of googling have not resulted in any clues.

**Comment by rgbriggs** [comment]
On 2018-10-14 15:45, TyMac wrote:
> Attempting to use the PCI DSS rules on ubuntu 16.04, I get an error when loading the 10.2.5.b rules:
> 
> `auditctl -a always,exit -F arch=b64 -S setuid -F a0=0 -F exe=/bin/su -F key=10.2.5.b-elevated-privs-session
> -F unknown field: exe`
> 
> Not sure why this rule does not work and large amounts of googling have not resulted in any clues.

This would be an outdated userspace or kernel.

In this particular case, it appears to be userspace that didn't know
about it. (audit-2.5.0) ("87b9af8 Add audit by process name support to
auditctl")

If it were kernel, it would return something like "Error sending add
rule data request (EINVAL)". (kernel-4.3) ("34d99af5 audit: implement
audit by executable")

**Comment by stevegrubb** [comment]
What version of audit user space are you using?

**Comment by stevegrubb** [comment]
Closing this out. It seems like an old user space is the culprit. If there is any further information that should be considered, please re-open this issue. Thanks.
