### ISSUE TITLE
Cannot read from af_unix plugin socket

### ISSUE THREAD

**Issue by albertomn86** [linux-audit/audit-userspace#74]
I was using the `audispd` tool (in previous version 2.8.3) to get the `auditd` output directly from a socket. It was configured using the default plugin configuration set in `af_unix.conf`:

```
active = yes
direction = out
path = builtin_af_unix
type = builtin
args = 0640 /var/run/audispd_events
format = string
```

Now I've upgraded to **Audit 3.0** in Fedora 29 and I realized that `audispd` was merged into `auditd`. So I enabled the plugin again in the new location `/etc/audit/plugins.d/af_unix.conf`, but now I cannot read from the socket using the same configuration.
I'm able to read the log directly from audit.log, so `auditd` is working as expected.

The installed audit version is: _audit-3.0-0.4.20180831git0047a6c.fc29.x86_64_

audit.rules:
```
## This set of rules is to suppress the performance effects of the
## audit system. The result is that you only get hardwired events.
-D

## This suppresses syscall auditing for all tasks started
## with this rule in effect.  Remove it if you need syscall
## auditing.
#-a task,never
-w /etc/shadow -p w
```

Is there any new configuration that I should apply to activate the socket?

Thanks in advance.

**Comment by stevegrubb** [comment]
Yes. This appears to be a problem because af_unix connections are not seen. audispd used poll and auditd uses libev. The af_unix handler needs porting to libev.

**Comment by stevegrubb** [comment]
Commit 6d6c65e should fix this
