### ISSUE TITLE
BUG: auditd should not depend on CAP_AUDIT_READ

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-userspace#75]
In commit 183775f155cb96d8012c2d493041a03f1b825b2f ("Do capabilities
check rather than uid") a switch was made from checking "getuid() != 0"
to checking CAP_AUDIT_CONTROL and CAP_AUDIT_READ via audit_can_control()
and audit_can_read().

auditd does not use the multicast socket, so there is no need for it
to check or have CAP_AUDIT_READ.

Having audit_can_read() available in lib/libaudit.c is certainly useful
regardless for other potential libaudit users like systemd.

Please see discussion at https://www.redhat.com/archives/linux-audit/2018-November/msg00069.html

**Comment by stevegrubb** [comment]
What bug does this cause?

**Comment by stevegrubb** [comment]
Should be fixed by commit 501b53c.
