### ISSUE TITLE
[Documentation Request] Which events are recorded by default when auditctl -l lists none?

### ISSUE THREAD

**Issue by q2dg** [linux-audit/audit-userspace#82]
Hello.

I want to record SSH login attempts with Auditd service. It works just fine but I don't understand one thing: I haven't defined any rule in /etc/audit/rules.d/*.rules file (that's is, auditctl -l shows nothing) but anyway Auditd is able to record these events (and more that I'm not interested). Why? Why auditd is able to get login attempts if I haven't any defined rule in *.rules file?

I though (surely wrongly) that rule files were the place to specify which kind of events you wanted to record, so not writing any rule should become in not recording any event, but they are. So there must be another place where Auditd has the list of "available to record" events. Where can I see what Auditd is able to record into audit.log and what not? I haven't found any beginner-friendly documentation explaining this.

Thanks a lot.

**Comment by q2dg** [comment]
Ah, understood!
Thanks a lot for your kind explanation
I'll close this issue, then, if you don't mind, as it can be searched by anyone as a reference

**Comment by stevegrubb** [comment]
I added a cleaned up version of the above explanation to the audit.rules man page at the very bottom. It'' be in the next release.
