### ISSUE TITLE
RFE: add support for AUDIT_INTEGRITY_EVM_XATTR records

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-userspace#85]
As of https://github.com/linux-audit/audit-kernel/commit/fa516b66a1bfce1d72f1620c54bdfebc493000d1 support was added in the kernel for the AUDIT_INTEGRITY_EVM_XATTR record with the EVM_ADD_XATTRS config option.  Its record number is 1806.  It has a field "xattr=" with result field "res=".

**Comment by rgbriggs** [comment]
Posted v1: https://www.redhat.com/archives/linux-audit/2019-April/msg00028.html

**Comment by stevegrubb** [comment]
Applied. Thanks.
