### ISSUE TITLE
Python2 bindings fail to cross compile

### ISSUE THREAD

**Issue by CameronNemo** [linux-audit/audit-userspace#87]
```
checking whether to create python bindings... testing
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
configure: error: Python explicitly requested and python headers were not found
make: *** [Makefile:428: config.status] Error 1
```

Working around this by not building python2 bindings. Not sure if anyone will notice they are gone.

**Comment by stevegrubb** [comment]
What version are you using?

**Comment by CameronNemo** [comment]
2.8.5

**Comment by stevegrubb** [comment]
Do you want to share the workaround so that it can be evaluated for merging?

**Comment by CameronNemo** [comment]
`sed -i "s;^PYINCLUDEDIR=.*;PYINCLUDEDIR=${XBPS_CROSS_BASE}/usr/include/python${py2_ver};" configure`

Where XBPS_CROSS_BASE is something like `aarch64-unknown-linux-gnu`.

**Comment by stevegrubb** [comment]
I'm going to close this out. Thanks for reporting it. Cross compiling seems non-operational for other reasons.
