### ISSUE TITLE
BUG: DAEMON_{CONFIG,ROTATE,RESUME} records triggered by SIGNAL_INFO inconsistent

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-userspace#90]
Records that are triggered by an AUDIT_SIGNAL_INFO message including AUDIT_DAEMON_CONFIG (HUP), AUDIT_DAEMON_ROTATE (USR1), AUDIT_DAEMON_RESUME (USR2) and AUDIT_DAEMON_END (TERM) have inconsistent reporting of signal info and swinging field "state".

They also assume that an empty security context implies there is no other useful information in the AUDIT_SIGNAL_INFO message so don't use the information that is there.

`AUDIT_DAEMON_CONFIG` swinging field "state":
- `op=reconfigure state=changed auid...`
- `op=reconfigure state=no-change auid...`
- `op=hup-info auid...` 

`AUDIT_DAEMON_RECONFIG` (stale?):
- `op=reconfigure state=no-change auid...`

`AUDIT_DAEMON_ROTATE` and `AUDIT_DAEMON_RESUME` don't list valid `auid` and `pid` values even when sent valid `AUDIT_SIGNAL_INFO` messages:
- `killall -USR2 auditd`:
- `type=DAEMON_ROTATE msg=audit(2019-04-09 11:44:07.746:5708) : op=rotate-logs auid=unset pid=-1 subj=?`
- `killall -USR1 auditd`:
- `type=DAEMON_RESUME msg=audit(2019-04-09 11:44:01.034:5707) : op=resume-logging auid=unset pid=-1 subj=? res=success`

**Comment by stevegrubb** [comment]
I fixed the missing state field. I don't know what you are saying is wrong with DAEMON_RECONFIG. I can't reproduce the problem you are saying exists for AUDIT_DAEMON_ROTATE and AUDIT_DAEMON_RESUME.

**Comment by rgbriggs** [comment]
Post v1: https://www.redhat.com/archives/linux-audit/2019-April/msg00082.html

**Comment by rgbriggs** [comment]
2019-05-10 Post v2: https://www.redhat.com/archives/linux-audit/2019-May/msg00016.html

**Comment by stevegrubb** [comment]
This went in as commit 947002f.

**Comment by rgbriggs** [comment]
Staged in audit-userspace: 947002fe5818 ("sig_info: use standard template for log messages")
and: 4ec1d456c6ca ("Add missing :")
