### ISSUE TITLE
BUG: the name field in audit log does not have a relative path when deleting directory

### ISSUE THREAD

**Issue by leekasong** [linux-audit/audit-userspace#98]
my current working directory is /home/kslee

when i execute "touch test_dir/hello", auditd fills the name field with "test_dir/hello" as shown below.

![image](https://user-images.githubusercontent.com/23168877/58314296-2bdb9000-7e4a-11e9-8f3b-c41240933db0.png)

when i execute "rm -rf test_dir", auditd logs two events of removal(test_dir/hello, test_dir).
i expected to have filled "test_dir/hello" in the name field , but it has only "hello" as shown below.

![rmrf](https://user-images.githubusercontent.com/23168877/58315458-9261ad80-7e4c-11e9-8396-6eb42a229b28.png)

these pictures are result of executing "tail -f /var/log/audit/audit.log"

and before the "touch" and "rm -rf", I ran "auditctl -a always,exit -S all -F dir=/home -F perm=w -F uid!=0 -F key=sysmgr_write_key".

**Comment by rgbriggs** [comment]
On 2019-05-24 02:11, leekasong wrote:
> when i execute "rm -rf test_dir", auditd logs two events of removal(test_dir/hello, test_dir).
> i expected to have filled "test_dir/hello" in the name field , but it has only "hello" as shown below.

I noticed exactly the same problem yesterday while running a set of unrelated tests and was about to file a bug, but you've beaten me to it.

You've not decoded the events (using ausearch -i) so we can't easily see what syscall it was, but I'm assuming it is unlinkat (and rmdir?).

This is a kernel issue and should be filed with https://github.com/linux-audit/audit-kernel

**Comment by leekasong** [comment]
> On 2019-05-24 02:11, leekasong wrote: when i execute "rm -rf test_dir", auditd logs two events of removal(test_dir/hello, test_dir). i expected to have filled "test_dir/hello" in the name field , but it has only "hello" as shown below.
> I noticed exactly the same problem yesterday while running a set of unrelated tests and was about to file a bug, but you've beaten me to it. You've not decoded the events (using ausearch -i) so we can't easily see what syscall it was, but I'm assuming it is unlinkat (and rmdir?). This is a kernel issue and should be filed with https://github.com/linux-audit/audit-kernel

yes syscall is unlinkat

![image](https://user-images.githubusercontent.com/23168877/58389280-0aee8700-8064-11e9-8136-3d43c84bb0f6.png)

**Comment by stevegrubb** [comment]
Since a new issue was opened in the kernel side, I'm closing out the user space side.
