### ISSUE TITLE
Changelog: Add information about unescaping in interptet events (AUDIT_TRUSTED_APP)

### ISSUE THREAD

**Issue by dimv36** [linux-audit/audit-userspace#99]
Hi,

How can I understand, changes from https://github.com/linux-audit/audit-userspace/pull/92 are merged now into master branch. But I can not find any information in Changelog file.

Can you add information about those change? It may be useful for other users that uses auditd.

**Comment by stevegrubb** [comment]
Fixed in commit 9bb93e9

**Comment by dimv36** [comment]
Thanks!
